/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Handy Service Full App Flutter V3
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Edit": "Edit",
          "Product History": "Product History",
          "Favorite": "Favorite",
          "Language": "Language",
          "Popular": "Popular",
          "Change Password": "Change Password",
          "Contact Us": "Contact Us",
          "Chats": "Chats",
          "Help": "Help",
          "Your Address": "Your Address",
          "Wallet": "Wallet",
          "Refer & Earn": "Refer & Earn",
          "About us": "About us",
          "Logout": "Logout",
          "Login / Register": "Login / Register",
          "New": "New",
          "Add New Address": "Add New Address",
          "Update Address": "Update Address",
          "Address": "Address",
          "House / Flat No": "House / Flat No",
          "Landmark": "Landmark",
          "Zipcode": "Zipcode",
          "SAVE AS": "SAVE AS",
          "Home": "Home",
          "Work": "Work",
          "Other": "Other",
          "Submit": "Submit",
          "Update": "Update",
          "Add New Card": "Add New Card",
          "Email Address": "Email Address",
          "Card Holder Name": "Card Holder Name",
          "Card Number": "Card Number",
          "CVV": "CVV",
          "MM/YY": "MM/YY",
          "ADD CARD": "ADD CARD",
          "Please rate the quality of service for the order": "Please rate the quality of service for the order",
          "Your comments and suggesstions help us improve the service quality better!": "Your comments and suggesstions help us improve the service quality better!",
          "Write Notes": "Write Notes",
          "Add Review": "Add Review",
          "Save": "Save",
          "Cancle": "Cancle",
          "Add+": "Add+",
          "Are you sure": "Are you sure",
          "To delete Address ?": "To delete Address ?",
          "Cancel": "Cancel",
          "Delete": "Delete",
          "year experience": "year experience",
          "My Appointment": "My Appointment",
          "Item Total": "Item Total",
          "Item discount": "Item discount",
          "Distance Charge": "Distance Charge",
          "Taxes and Charges": "Taxes and Charges",
          "Grand Total": "Grand Total",
          "Booking Details": "Booking Details",
          "Appointment Number": "Appointment Number",
          "Payment": "Payment",
          "Your Appoinments Status": "Your Appoinments Status",
          "Select date of service": "Select date of service",
          "No Slots Found": "No Slots Found",
          "Time to start service": "Time to start service",
          "to": "to",
          "Chekout": "Chekout",
          "Message...": "Message...",
          "min duration": "min duration",
          "View": "View",
          "Notes for service": "Notes for service",
          "Offers & Benefits": "Offers & Benefits",
          "Apply Coupon": "Apply Coupon",
          "Apply Wallet Coin": "Apply Wallet Coin",
          "Bill Details": "Bill Details",
          "To Pay": "To Pay",
          "Payment Method": "Payment Method",
          "Please Add Your Address": "Please Add Your Address",
          "Pay": "Pay",
          "Access Your": "Access Your",
          "Location": "Location",
          "Use Current Location": "Use Current Location",
          "Choose Location": "Choose Location",
          "Password": "Password",
          "Login": "Login",
          "Use coupon code": "Use coupon code",
          "- Valid until": "- Valid until",
          "Apply": "Apply",
          "Choose From": "Choose From",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Email": "Email",
          "Search": "Search",
          "Start typing to search": "Start typing to search",
          "Code": "Code",
          "Phone": "Phone",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again.": "Please check and try again.",
          "retry": "retry",
          "Chat with us": "Chat with us",
          "Search location": "Search location",
          "USE MY CURRENT LOCATION": "USE MY CURRENT LOCATION",
          "Forgot Passwrord": "Forgot Passwrord",
          "OTP Verification": "OTP Verification",
          "Please enter your credentials": "Please enter your credentials",
          "Send OTP": "Send OTP",
          "An authentication code hase been sent to": "An authentication code hase been sent to",
          "Verification code": "Verification code",
          "Verify": "Verify",
          "ADD": "ADD",
          "Items": "Items",
          "Checkout": "Checkout",
          "hr": "hr",
          "Book Now": "Book Now",
          "Buy Products": "Buy Products",
          "Info": "Info",
          "Review": "Review",
          "Service Provided": "Service Provided",
          "Descriptions": "Descriptions",
          "Contact Detail": "Contact Detail",
          "Opps, Please Login or Register first!": "Opps, Please Login or Register first!",
          "Ongoing": "Ongoing",
          "Past": "Past",
          "Search Here": "Search Here",
          "Special Offer": "Special Offer",
          "Categories": "Categories",
          "See All": "See All",
          "Recomended": "Recomended",
          "Products": "Products",
          "Sign in": "Sign in",
          "Welcome Back!": "Welcome Back!",
          "Email and phone Number": "Email and phone Number",
          "Forgot Password?": "Forgot Password?",
          "Dont have an account?": "Dont have an account?",
          "Register": "Register",
          "Delivery Charge": "Delivery Charge",
          "Sold By": "Sold By",
          "Highlight": "Highlight",
          "Disclaimer": "Disclaimer",
          "Related Products": "Related Products",
          "Images": "Images",
          "My Order": "My Order",
          "Order Details": "Order Details",
          "Order Status": "Order Status",
          "Order Number": "Order Number",
          "Your Order Status": "Your Order Status",
          "Share With Friends": "Share With Friends",
          "Invite Now": "Invite Now",
          "Sign up": "Sign up",
          "Welcome": "Welcome",
          "Email or phone number": "Email or phone number",
          "Referal Code (Optional)": "Referal Code (Optional)",
          "Confirm Password": "Confirm Password",
          "Alredy have an account?": "Alredy have an account?",
          "Add Service": "Add Service",
          "Remove Service": "Remove Service",
          "Duration": "Duration",
          "most rated": "most rated",
          "Sort": "Sort",
          "Filter": "Filter",
          "Please rate the quality of product for the order": "Please rate the quality of product for the order",
          "Get Started": "Get Started",
          "No Internet Connection": "No Internet Connection",
          "Please wait": "Please wait",
          "Expiry": "Expiry",
          "Pay With Stripe": "Pay With Stripe",
          "Book Service": "Book Service",
          "Back to Home": "Back to Home",
          "All Transaction": "All Transaction",
          "DEPOSIT": "DEPOSIT",
          "WITHDRAW": "WITHDRAW",
          "Welcome to Handyman": "Welcome to Handyman",
          "Continue with Email": "Continue with Email",
          "Continue with Phone Number": "Continue with Phone Number",
          "My Account": "My Account",
          "All fields are required": "All fields are required",
          "Could not determine your location": "Could not determine your location",
          "Successfully Added": "Successfully Added",
          "Successfully Updated": "Successfully Updated",
          "Card Information Saved": "Card Information Saved",
          "Add Product Review": "Add Product Review",
          "Please add comments": "Please add comments",
          "Review Saved": "Review Saved",
          "Select Address": "Select Address",
          "Appointment Detail": "Appointment Detail",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Created": "Created",
          "Accepted": "Accepted",
          "Rejected by Freelancer": "Rejected by Freelancer",
          "Completed": "Completed",
          "Cancelled": "Cancelled",
          "Refunded": "Refunded",
          "Delayed": "Delayed",
          "Status Updated": "Status Updated",
          "Please select Slot": "Please select Slot",
          "Booking": "Booking",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Please select payment method": "Please select payment method",
          "Sorry we deliver the order near to": "Sorry we deliver the order near to",
          "Thank You!": "Thank You!",
          "For Your Order": "For Your Order",
          "TRACK MY ORDER": "TRACK MY ORDER",
          "BACK TO HOME": "BACK TO HOME",
          "Location services are disabled.": "Location services are disabled.",
          "Location permissions are denied": "Location permissions are denied",
          "Location permissions are permanently denied, we cannot request permissions.": "Location permissions are permanently denied, we cannot request permissions.",
          "Select Coupon": "Select Coupon",
          "Please select offer": "Please select offer",
          "update": "update",
          "FAQ": "FAQ",
          "Find Location": "Find Location",
          "Freelancer Products": "Freelancer Products",
          "We already have product with other freelancer": "We already have product with other freelancer",
          "Booking History": "Booking History",
          "Inbox": "Inbox",
          "Email is not valid": "Email is not valid",
          "Notification": "Notification",
          "Popular Product": "Popular Product",
          "Product Category": "Product Category",
          "Product Checkout": "Product Checkout",
          "Product Detail": "Product Detail",
          "Something went wrong": "Something went wrong",
          "password does not match": "password does not match",
          "Service Detail": "Service Detail",
          "Are you sure?": "Are you sure?",
          "Orders once placed cannot be cancelled and are non-refundable": "Orders once placed cannot be cancelled and are non-refundable",
          "Yes, Place Order": "Yes, Place Order",
          "Please select card": "Please select card",
          "Creating Order": "Creating Order",
          "Track Booking": "Track Booking",
          "FAQs": "FAQs",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Terms & Conditions": "Terms & Conditions",
          "Privacy Policy": "Privacy Policy",
          "to delete Address ?": "to delete Address ?",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.": "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.",
          "Door to Door Supprot": "Door to Door Supprot",
          "Easy Track Order": "Easy Track Order",
          "Appointment ID": "Appointment ID",
          "Wallet Discount": "Wallet Discount",
          "Apply Coupon Code": "Apply Coupon Code",
          "Coupon Applied :": "Coupon Applied :",
          "Available Balance": "Available Balance",
          "Complaints": "Complaints",
          "Issue With": "Issue With",
          "Freelancer": "Freelancer",
          "Select Freelancer": "Select Freelancer",
          "Select product": "Select product",
          "Select service": "Select service",
          "Select Reason": "Select Reason",
          "Title": "Title",
          "Brief of your issue": "Brief of your issue",
          "Comments": "Comments",
          "Write something on issue": "Write something on issue",
          "Upload Image": "Upload Image",
          "Full Name": "Full Name",
          "Message": "Message",
          " - Valid until": " - Valid until",
          "Verify your phone number": "Verify your phone number",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Enter your email address or phone number and we will send a verification code to generate a new password",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Update Password": "Update Password",
          "No Data Found": "No Data Found",
          "No New Appointments Found": "No New Appointments Found",
          "No Ongoing Appointments Found": "No Ongoing Appointments Found",
          "No Past Appointments Found": "No Past Appointments Found",
          "No Data Found Near You!": "No Data Found Near You!",
          "Booking Cancel": "Booking Cancel",
          "Thank You! Your transaction is completed. tis is test": "Thank You! Your transaction is completed. tis is test",
          "No New Order Found": "No New Order Found",
          "No Ongoing Order Found": "No Ongoing Order Found",
          "No Past Order Found": "No Past Order Found",
          "Order ID": "Order ID",
          "Please enter valid details": "Please enter valid details",
          "Handymans": "Handymans",
          "Popularity": "Popularity",
          "Price - Low to High": "Price - Low to High",
          "Price - Price High to Low": "Price - Price High to Low",
          "A - Z": "A - Z",
          "Z - A": "Z - A",
          "Experience": "Experience",
          "Your Booking Code:": "Your Booking Code:",
          "All Transactions": "All Transactions",
          "Panding Payment": "Panding Payment",
          "Could not launch": "Could not launch",
          "Choose": "Choose",
          "Chat": "Chat",
          "Category": "Category",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
          "The product arrived too late": "The product arrived too late",
          "he product did not match the description": "he product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective": "The product was damaged or defective",
          "The merchant shipped the wrong item": "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped": "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Freelacer behavior": "Freelacer behavior",
          "Issue with Payment Amount": "Issue with Payment Amount",
          "Others": "Others",
          "Freelancer arrived too late": "Freelancer arrived too late",
          "Freelancer did not match the description": "Freelancer did not match the description",
          "Freelancer was fraudulent": "Freelancer was fraudulent",
          "Related to service": "Related to service",
          "Satisfaction of services": "Satisfaction of services",
          "Choose Issue With": "Choose Issue With",
          "Choose Reason": "Choose Reason",
          "Choose Service": "Choose Service",
          "Choose Product": "Choose Product",
          "Complaints registered": "Complaints registered",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "Contact Information Sent": "Contact Information Sent",
          "Alert!": "Alert!",
          "Okay": "Okay",
          "Edit Profile": "Edit Profile",
          "Something went wrong while signup": "Something went wrong while signup",
          "error": "error",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Password mismatch": "Password mismatch",
          "Password Updated": "Password Updated",
          "Access denied": "Access denied",
          "Phone Number is required": "Phone Number is required",
          "Product Order History": "Product Order History",
          "Product Listing": "Product Listing",
          "Product Order Detail": "Product Order Detail",
          "Your friend": "Your friend",
          "has invited you to": "has invited you to",
          "Hey Buddy download": "Hey Buddy download",
          "rom app store and use my code": "rom app store and use my code",
          "Share with buddies": "Share with buddies",
          "while sign up we both will get": "while sign up we both will get",
          "wallet amount": "wallet amount",
          "Copied to clipboard": "Copied to clipboard",
          "Use this code for verification": "Use this code for verification",
          "Don't share this otp to anybody else": "Don't share this otp to anybody else",
          "phone verification": "phone verification",
          "Getting Rewards": "Getting Rewards",
          "Congratulations your friend have received the": "Congratulations your friend have received the",
          "Congratulations you have received the": "Congratulations you have received the",
          "Congratulations you & your friend have received the": "Congratulations you & your friend have received the",
          "Congratulation": "Congratulation",
          "Close": "Close",
          "Ok": "Ok",
          "Price L-H": "Price L-H",
          "Price H-L": "Price H-L",
          "A-Z": "A-Z",
          "Z-A": "Z-A",
          "Single Product Review": "Single Product Review",
          "Subcategory": "Subcategory",
          "Top Freelancers": "Top Freelancers",
          "Top Products": "Top Products",
          "Service Appointments": "Service Appointments",
          "Product Orders": "Product Orders",
          "Profile": "Profile",
          "About Us": "About Us",
          "Connection failed!": "Connection failed!",
          "Warning": "Warning",
          "Clear Cart": "Clear Cart",
          "You already have item's in cart with different grocery store": "You already have item's in cart with different grocery store",
          "Session expired!": "Session expired!",
          "History": "History",
          "Shop": "Shop",
          "Account": "Account",
          "Confirm Location": "Confirm Location",
          "Use My Current Location": "Use My Current Location",
          "Featching Location": "Featching Location",
          "We already have service in cart with another freelancer": "We already have service in cart with another freelancer"
        },
        "hi_IN": {
          "Edit": "संपादन करना",
          "Product History": "उत्पाद इतिहास",
          "Favorite": "पसंदीदा",
          "Language": "भाषा",
          "Popular": "लोकप्रिय",
          "Change Password": "पासवर्ड बदलें",
          "Contact Us": "संपर्क करें",
          "Chats": "चैट",
          "Help": "मदद करना",
          "Your Address": "तुम्हारा पता",
          "Wallet": "बटुआ",
          "Refer & Earn": "देखें और कमाएं",
          "About us": "हमारे बारे में",
          "Logout": "लॉग आउट",
          "Login / Register": "लॉग इन / रजिस्टर",
          "New": "नया",
          "Add New Address": "नया पता जोड़ें",
          "Update Address": "पता अपडेट करें",
          "Address": "पता",
          "House / Flat No": "मकान/फ्लैट नं",
          "Landmark": "सीमाचिह्न",
          "Zipcode": "पिन कोड",
          "SAVE AS": "के रूप रक्षित करें",
          "Home": "घर",
          "Work": "काम",
          "Other": "अन्य",
          "Submit": "प्रस्तुत करना",
          "Update": "अद्यतन",
          "Add New Card": "नया कार्ड जोड़ें",
          "Email Address": "ईमेल पता",
          "Card Holder Name": "कार्डधारक का नाम",
          "Card Number": "कार्ड नंबर",
          "CVV": "सीवीवी",
          "MM/YY": "महीना साल",
          "ADD CARD": "कार्ड जोड़ें",
          "Please rate the quality of service for the order": "कृपया आदेश के लिए सेवा की गुणवत्ता का मूल्यांकन करें",
          "Your comments and suggesstions help us improve the service quality better!": "आपकी टिप्पणियों और सुझावों से हमें सेवा की गुणवत्ता को बेहतर बनाने में मदद मिलती है!",
          "Write Notes": "नोट लिख",
          "Add Review": "समीक्षा जोड़ें",
          "Save": "बचाना",
          "Cancle": "कैंक्ल",
          "Add+": "जोड़ें+",
          "Are you sure": "क्या आपको यकीन है",
          "To delete Address ?": "पता मिटाने के लिए ?",
          "Cancel": "रद्द करना",
          "Delete": "मिटाना",
          "year experience": "वर्ष का अनुभव",
          "My Appointment": "मेरी नियुक्ति",
          "Item Total": "आइटम का कुल",
          "Item discount": "आइटम छूट",
          "Distance Charge": "दूरी प्रभार",
          "Taxes and Charges": "कर और शुल्क",
          "Grand Total": "कुल योग",
          "Booking Details": "बुकिंग विवरण",
          "Appointment Number": "नियुक्ति संख्या",
          "Payment": "भुगतान",
          "Your Appoinments Status": "आपकी नियुक्तियों की स्थिति",
          "Select date of service": "सेवा की तिथि चुनें",
          "No Slots Found": "कोई स्लॉट नहीं मिला",
          "Time to start service": "सेवा शुरू करने का समय",
          "to": "से",
          "Chekout": "जांचें",
          "Message...": "संदेश...",
          "min duration": "अवधि",
          "View": "देखना",
          "Notes for service": "सेवा के लिए नोट्स",
          "Offers & Benefits": "ऑफ़र और लाभ",
          "Apply Coupon": "कूपन लागू करें",
          "Apply Wallet Coin": "वॉलेट सिक्का लागू करें",
          "Bill Details": "बिल विवरण",
          "To Pay": "भुगतान करने के लिए",
          "Payment Method": "भुगतान का तरीका",
          "Please Add Your Address": "कृपया अपना पता जोड़ें",
          "Pay": "भुगतान करना",
          "Access Your": "अपना प्रवेश करें",
          "Location": "स्थान",
          "Use Current Location": "वर्तमान स्थान का उपयोग करें",
          "Choose Location": "स्थान का चयन",
          "Password": "पासवर्ड",
          "Login": "लॉग इन करें",
          "Use coupon code": "कूपन कोड का प्रयोग करें",
          "- Valid until": "- तब तक वैध",
          "Apply": "आवेदन करना",
          "Choose From": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Gender": "लिंग",
          "Male": "पुरुष",
          "Female": "महिला",
          "Email": "ईमेल",
          "Search": "खोज",
          "Start typing to search": "खोजने के लिए टाइप करना प्रारंभ करें",
          "Code": "कोड",
          "Phone": "फ़ोन",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again.": "कृपया जाँच करें और पुनः प्रयास करें।",
          "retry": "पुन: प्रयास करें",
          "Chat with us": "हमारे साथ चैट करें",
          "Search location": "स्थान खोजें",
          "USE MY CURRENT LOCATION": "मेरे वर्तमान स्थान का उपयोग करें",
          "Forgot Passwrord": "पासवर्ड भूल गए",
          "OTP Verification": "ओटीपी सत्यापन",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "Send OTP": "OTP भेजें",
          "An authentication code hase been sent to": "एक प्रमाणीकरण कोड भेजा गया है",
          "Verification code": "पुष्टि संख्या",
          "Verify": "सत्यापित करना",
          "ADD": "जोड़ें",
          "Items": "आइटम्स",
          "Checkout": "चेकआउट",
          "hr": "घंटे",
          "Book Now": "अभी बुक करें",
          "Buy Products": "उत्पाद खरीदें",
          "Info": "जानकारी",
          "Review": "समीक्षा",
          "Service Provided": "सेवा प्रदान की",
          "Descriptions": "विवरण",
          "Contact Detail": "संपर्क विवरण",
          "Opps, Please Login or Register first!": "ओह, कृपया पहले लॉगिन करें या रजिस्टर करें!",
          "Ongoing": "चल रहे",
          "Past": "अतीत",
          "Search Here": "यहां तलाश करो",
          "Special Offer": "विशेष पेशकश",
          "Categories": "श्रेणियाँ",
          "See All": "सभी देखें",
          "Recomended": "सिफारिश",
          "Products": "उत्पादों",
          "Sign in": "साइन इन करें",
          "Welcome Back!": "वापसी पर स्वागत है!",
          "Email and phone Number": "ईमेल और फोन नंबर",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Dont have an account?": "खाता नहीं है?",
          "Register": "पंजीकरण करवाना",
          "Delivery Charge": "डिलीवरी चार्ज",
          "Sold By": "द्वारा बेचा",
          "Highlight": "प्रमुखता से दिखाना",
          "Disclaimer": "अस्वीकरण",
          "Related Products": "संबंधित उत्पाद",
          "Images": "इमेजिस",
          "My Order": "मेरा आदेश",
          "Order Details": "ऑर्डर का विवरण",
          "Order Status": "आदेश की स्थिति",
          "Order Number": "क्रम संख्या",
          "Your Order Status": "आपके आदेश की स्थिति",
          "Share With Friends": "दोस्तों के साथ बांटें",
          "Invite Now": "अभी आमंत्रित करें",
          "Sign up": "साइन अप करें",
          "Welcome": "स्वागत",
          "Email or phone number": "ईमेल या फोन नंबर",
          "Referal Code (Optional)": "रेफ़रल कोड (वैकल्पिक)",
          "Confirm Password": "पासवर्ड पुष्टि करें",
          "Alredy have an account?": "क्या आपके पास खाता है?",
          "Add Service": "सर्विस जोड़ें",
          "Remove Service": "सर्विस निकालें",
          "Duration": "अवधि",
          "most rated": "सर्वाधिक श्रेणीकृत",
          "Sort": "क्रम से लगाना",
          "Filter": "फ़िल्टर",
          "Please rate the quality of product for the order": "कृपया ऑर्डर के लिए उत्पाद की गुणवत्ता को रेट करें",
          "Get Started": "आरंभ करें",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Please wait": "कृपया प्रतीक्षा करें",
          "Expiry": "समाप्ति",
          "Pay With Stripe": "स्ट्राइप के साथ भुगतान करें",
          "Book Service": "बुक सर्विस",
          "Back to Home": "घर वापस",
          "All Transaction": "सभी लेन-देन",
          "DEPOSIT": "जमा",
          "WITHDRAW": "वापस लेना",
          "Welcome to Handyman": "अप्रेंटिस में आपका स्वागत है",
          "Continue with Email": "ईमेल के साथ जारी रखें",
          "Continue with Phone Number": "फ़ोन नंबर के साथ जारी रखें",
          "My Account": "मेरा खाता",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Could not determine your location": "आपका स्थान निर्धारित नहीं कर सका",
          "Successfully Added": "सफलतापूर्वक जोड़ा गया",
          "Successfully Updated": "अद्यतन हो गया",
          "Card Information Saved": "कार्ड की जानकारी सहेजी गई",
          "Add Product Review": "उत्पाद समीक्षा जोड़ें",
          "Please add comments": "कृपया टिप्पणी जोड़ें",
          "Review Saved": "समीक्षा सहेजी गई",
          "Select Address": "पता चुनें",
          "Appointment Detail": "नियुक्ति विवरण",
          "COD": "कैश ऑन डिलीवरी",
          "Stripe": "Stripe",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रेज़रपे",
          "Instamojo": "इंस्टामोजो",
          "Paystack": "पेस्टैक",
          "Flutterwave": "Flutterwave",
          "Created": "बनाया था",
          "Accepted": "स्वीकार किया हुआ",
          "Rejected by Freelancer": "फ्रीलांसर द्वारा अस्वीकृत",
          "Completed": "पूरा किया हुआ",
          "Cancelled": "रद्द किया गया",
          "Refunded": "वापसी की गई है",
          "Delayed": "देर से",
          "Status Updated": "स्थिति अपडेट",
          "Please select Slot": "कृपया स्लॉट का चयन करें",
          "Booking": "बुकिंग",
          "Sunday": "रविवार",
          "Monday": "सोमवार",
          "Tuesday": "मंगलवार",
          "Wednesday": "बुधवार",
          "Thursday": "गुरुवार",
          "Friday": "शुक्रवार",
          "Saturday": "शनिवार",
          "Please select payment method": "कृपया भुगतान विधि चुनें",
          "Sorry we deliver the order near to": "क्षमा करें, हम ऑर्डर को निकट पहुंचाते हैं",
          "Thank You!": "धन्यवाद!",
          "For Your Order": "आपके ऑर्डर के लिए",
          "TRACK MY ORDER": "मेरी आर्डर का पता लगाओ",
          "BACK TO HOME": "घर वापस",
          "Location services are disabled.": "स्थान सेवाएं अक्षम हैं।",
          "Location permissions are denied": "स्थान अनुमतियां अस्वीकार कर दी गई हैं",
          "Location permissions are permanently denied, we cannot request permissions.": "स्थान अनुमतियों को स्थायी रूप से अस्वीकार कर दिया गया है, हम अनुमतियों का अनुरोध नहीं कर सकते।",
          "Select Coupon": "कूपन चुनें",
          "Please select offer": "कृपया ऑफ़र चुनें",
          "update": "अपडेट करें",
          "FAQ": "सामान्य प्रश्न",
          "Find Location": "स्थान खोजें",
          "Freelancer Products": "फ्रीलांसर उत्पाद",
          "We already have product with other freelancer": "हमारे पास पहले से ही अन्य फ्रीलांसर के साथ उत्पाद है",
          "Booking History": "बुकिंग इतिहास",
          "Inbox": "इनबॉक्स",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "Notification": "अधिसूचना",
          "Popular Product": "लोकप्रिय उत्पाद",
          "Product Category": "उत्पाद श्रेणी",
          "Product Checkout": "उत्पाद चेकआउट",
          "Product Detail": "उत्पाद माहिती",
          "Something went wrong": "कुछ गलत हो गया",
          "password does not match": "पासवर्ड मैच नहीं कर रहा है",
          "Service Detail": "सेवा विवरण",
          "Are you sure?": "क्या आपको यकीन है?",
          "Orders once placed cannot be cancelled and are non-refundable": "एक बार दिए गए आदेश रद्द नहीं किए जा सकते हैं और अप्रतिदेय हैं",
          "Yes, Place Order": "हां, ऑर्डर दें",
          "Please select card": "कृपया कार्ड चुनें",
          "Creating Order": "आदेश बनाना",
          "Track Booking": "ट्रैक बुकिंग",
          "FAQs": "पूछे जाने वाले प्रश्न",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "to delete Address ?": "पता मिटाने के लिए ?",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.":
              "प्रकाशन और ग्राफिक डिजाइन में लोरेम इप्सम एक भराव पाठ है जिसे आमतौर पर प्रदर्शित करने के लिए उपयोग किया जाता है।",
          "Door to Door Supprot": "डोर टू डोर सपोर्ट",
          "Easy Track Order": "आसान ट्रैक ऑर्डर",
          "Appointment ID": "अपॉइंटमेंट आईडी",
          "Wallet Discount": "वॉलेट छूट",
          "Apply Coupon Code": "कूपन कोड लागू करें",
          "Coupon Applied :": "कूपन लागू:",
          "Available Balance": "उपलब्ध शेष राशि",
          "Complaints": "शिकायतों",
          "Issue With": "मुद्दे के साथ",
          "Freelancer": "फ्रीलांसर",
          "Select Freelancer": "फ्रीलांसर का चयन करें",
          "Select product": "उत्पाद चुनें",
          "Select service": "सेवा का चयन करें",
          "Select Reason": "कारण चुनें",
          "Title": "शीर्षक",
          "Brief of your issue": "आपकी समस्या का संक्षिप्त विवरण",
          "Comments": "टिप्पणियाँ",
          "Write something on issue": "मुद्दे पर कुछ लिखें",
          "Upload Image": "तस्विर अपलोड करना",
          "Full Name": "पूरा नाम",
          "Message": "संदेश",
          " - Valid until": " - तब तक वैध",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "अपना ईमेल पता या फोन नंबर दर्ज करें और हम एक नया पासवर्ड बनाने के लिए एक सत्यापन कोड भेजेंगे",
          "Generate New Password": "नया पासवर्ड जनरेट करें",
          "New Password": "नया पासवर्ड",
          "Update Password": "पासवर्ड अपडेट करें",
          "No Data Found": "कोई डेटा नहीं मिला",
          "No New Appointments Found": "कोई नई नियुक्ति नहीं मिली",
          "No Ongoing Appointments Found": "कोई चालू नियुक्ति नहीं मिली",
          "No Past Appointments Found": "कोई पिछला अपॉइंटमेंट नहीं मिला",
          "No Data Found Near You!": "आपके आस-पास कोई डेटा नहीं मिला!",
          "Booking Cancel": "बुकिंग रद्द",
          "Thank You! Your transaction is completed. tis is test": "धन्यवाद! आपका लेनदेन पूरा हो गया है। टिस टेस्ट है",
          "No New Order Found": "कोई नया आदेश नहीं मिला",
          "No Ongoing Order Found": "कोई चालू आदेश नहीं मिला",
          "No Past Order Found": "कोई पिछला आदेश नहीं मिला",
          "Order ID": "आदेश ID",
          "Please enter valid details": "कृपया मान्य विवरण दर्ज करें",
          "Handymans": "अप्रेंटिस",
          "Popularity": "लोकप्रियता",
          "Price - Low to High": "कीमतों का उतार - चढ़ाव",
          "Price - Price High to Low": "मूल्य - मूल्य उच्च से निम्न",
          "A - Z": "ए - ज़ू",
          "Z - A": "जेड - ए",
          "Experience": "अनुभव",
          "Your Booking Code:": "आपका बुकिंग कोड:",
          "All Transactions": "सभी लेन - देन",
          "Panding Payment": "लंबित भुगतान",
          "Could not launch": "लॉन्च नहीं हो सका",
          "Choose": "चुनना",
          "Chat": "बात करना",
          "Category": "श्रेणी",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक किसी पृष्ठ की पठनीय सामग्री से उसके लेआउट को देखते हुए विचलित हो जाएगा।",
          "The product arrived too late": "उत्पाद बहुत देर से पहुंचा",
          "he product did not match the description": "वह उत्पाद विवरण से मेल नहीं खाता",
          "The purchase was fraudulent": "खरीद धोखाधड़ी थी",
          "The product was damaged or defective": "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत वस्तु भेज दी",
          "Wrong Item Size or Wrong Product Shipped": "गलत आइटम का आकार या गलत उत्पाद भेज दिया गया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचा",
          "Driver behavior": "चालक व्यवहार",
          "Freelacer behavior": "फ्रीलांसर व्यवहार",
          "Issue with Payment Amount": "भुगतान राशि के साथ समस्या",
          "Others": "अन्य",
          "Freelancer arrived too late": "फ्रीलांसर बहुत देर से पहुंचे",
          "Freelancer did not match the description": "फ्रीलांसर विवरण से मेल नहीं खाता",
          "Freelancer was fraudulent": "फ्रीलांसर धोखेबाज था",
          "Related to service": "सेवा से संबंधित",
          "Satisfaction of services": "सेवाओं की संतुष्टि",
          "Choose Issue With": "के साथ समस्या चुनें",
          "Choose Reason": "कारण चुनें",
          "Choose Service": "सेवा चुनें",
          "Choose Product": "उत्पाद चुनें",
          "Complaints registered": "शिकायतें दर्ज",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "Alert!": "चेतावनी!",
          "Okay": "ठीक",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "error": "गलती",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Access denied": "पहुंच अस्वीकृत",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Product Order History": "उत्पाद आदेश इतिहास",
          "Product Listing": "उत्पाद लिस्टिंग",
          "Product Order Detail": "उत्पाद आदेश विवरण",
          "Your friend": "आपके दोस्त",
          "has invited you to": "आपको आमंत्रित किया है",
          "Hey Buddy download": "अरे बडी डाउनलोड",
          "rom app store and use my code": "रोम ऐप स्टोर और मेरे कोड का उपयोग करें",
          "Share with buddies": "दोस्तों के साथ शेयर करें",
          "while sign up we both will get": "साइन अप करते समय हम दोनों को मिलेगा",
          "wallet amount": "बटुआ राशि",
          "Copied to clipboard": "क्लिपबोर्ड पर नकल",
          "Use this code for verification": "सत्यापन के लिए इस कोड का प्रयोग करें",
          "Don't share this otp to anybody else": "इस ओटीपी को किसी और को शेयर न करें",
          "phone verification": "फोन सत्यापन",
          "Getting Rewards": "पुरस्कार प्राप्त करना",
          "Congratulations your friend have received the": "बधाई हो आपके मित्र को मिल गया है",
          "Congratulations you have received the": "बधाई हो आपको मिली है",
          "Congratulations you & your friend have received the": "बधाई हो आपको और आपके मित्र ने प्राप्त किया है",
          "Congratulation": "बधाई",
          "Close": "बंद करना",
          "Ok": "ठीक",
          "Price L-H": "कीमत",
          "Price H-L": "कीमत एच-एल",
          "A-Z": "ए-जेड",
          "Z-A": "जेड-ए",
          "Single Product Review": "एकल उत्पाद समीक्षा",
          "Subcategory": "उपश्रेणी",
          "Top Freelancers": "शीर्ष फ्रीलांसर",
          "Top Products": "शीर्ष उत्पाद",
          "Service Appointments": "सेवा नियुक्ति",
          "Product Orders": "उत्पाद आदेश",
          "Profile": "प्रोफ़ाइल",
          "About Us": "हमारे बारे में",
          "Connection failed!": "कनेक्शन विफल!",
          "Warning": "चेतावनी",
          "Clear Cart": "कार्ट को खाली करें",
          "You already have item's in cart with different grocery store": "आपके पास पहले से ही विभिन्न किराने की दुकान के साथ कार्ट में आइटम हैं",
          "Session expired!": "सत्र समाप्त हुआ!",
          "History": "इतिहास",
          "Shop": "दुकान",
          "Account": "खाता",
          "Confirm Location": "स्थान की पुष्टि करें",
          "Use My Current Location": "मेरे वर्तमान स्थान का उपयोग करें",
          "Featching Location": "स्थान प्राप्त करना",
          "We already have service in cart with another freelancer": "हमारे पास पहले से ही एक अन्य फ्रीलांसर के साथ कार्ट में सेवा है"
        },
        "es_DE": {
          "Edit": "Editar",
          "Product History": "Historial del producto",
          "Favorite": "Favorito",
          "Language": "Idioma",
          "Popular": "Popular",
          "Change Password": "Cambia la contraseña",
          "Contact Us": "Contáctenos",
          "Chats": "charlas",
          "Help": "Ayuda",
          "Your Address": "Su dirección",
          "Wallet": "Cartera",
          "Refer & Earn": "Referir y ganar",
          "About us": "Sobre nosotros",
          "Logout": "Cerrar sesión",
          "Login / Register": "Iniciar sesión / Registrarse",
          "New": "Nuevo",
          "Add New Address": "Agregar nueva dirección",
          "Update Address": "Actualizar dirección",
          "Address": "Dirección",
          "House / Flat No": "Casa / Piso No",
          "Landmark": "Punto de referencia",
          "Zipcode": "Código postal",
          "SAVE AS": "GUARDAR COMO",
          "Home": "Hogar",
          "Work": "Trabajar",
          "Other": "Otro",
          "Submit": "Enviar",
          "Update": "Actualizar",
          "Add New Card": "Agregar nueva tarjeta",
          "Email Address": "Dirección de correo electrónico",
          "Card Holder Name": "Nombre del titular de la tarjeta",
          "Card Number": "Número de tarjeta",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "ADD CARD": "AGREGAR TARJETA",
          "Please rate the quality of service for the order": "Califique la calidad del servicio para el pedido.",
          "Your comments and suggesstions help us improve the service quality better!": "Sus comentarios y sugerencias nos ayudan a mejorar la calidad del servicio!",
          "Write Notes": "Escribe notas",
          "Add Review": "Agregar una opinión",
          "Save": "Ahorrar",
          "Cancle": "Cancelar",
          "Add+": "Agregar+",
          "Are you sure": "Está seguro",
          "To delete Address ?": "Para eliminar la dirección?",
          "Cancel": "Cancelar",
          "Delete": "Borrar",
          "year experience": "año de experiencia",
          "My Appointment": "Mi cita",
          "Item Total": "Total",
          "Item discount": "descuento del artículo",
          "Distance Charge": "Cargo por distancia",
          "Taxes and Charges": "Impuestos y Cargos",
          "Grand Total": "Gran total",
          "Booking Details": "Detalles de la reserva",
          "Appointment Number": "Número de cita",
          "Payment": "Pago",
          "Your Appoinments Status": "Estado de sus citas",
          "Select date of service": "Seleccionar fecha de servicio",
          "No Slots Found": "No se encontraron ranuras",
          "Time to start service": "Hora de iniciar el servicio",
          "to": "a",
          "Chekout": "Checalo",
          "Message...": "Mensaje...",
          "min duration": "duración",
          "View": "Vista",
          "Notes for service": "Notas para el servicio",
          "Offers & Benefits": "Ofertas y beneficios",
          "Apply Coupon": "Aplicar cupón",
          "Apply Wallet Coin": "Aplicar Monedero Monedero",
          "Bill Details": "Detalles de la factura",
          "To Pay": "Pagar",
          "Payment Method": "Método de pago",
          "Please Add Your Address": "Por favor agregue su dirección",
          "Pay": "Pagar",
          "Access Your": "Accede a tu",
          "Location": "Ubicación",
          "Use Current Location": "Usar ubicación actual",
          "Choose Location": "Elegir la ubicación",
          "Password": "Clave",
          "Login": "Acceso",
          "Use coupon code": "Usar código de cupón",
          "- Valid until": "- Válido hasta",
          "Apply": "Aplicar",
          "Choose From": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Gender": "Género",
          "Male": "Masculino",
          "Female": "Femenino",
          "Email": "Correo electrónico",
          "Search": "Búsqueda",
          "Start typing to search": "Empieza a escribir para buscar",
          "Code": "Código",
          "Phone": "Teléfono",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again.": "Por favor revisa e intenta de nuevo.",
          "retry": "rever",
          "Chat with us": "habla con nosotros",
          "Search location": "Buscar ubicación",
          "USE MY CURRENT LOCATION": "USAR MI UBICACIÓN ACTUAL",
          "Forgot Passwrord": "Olvidé mi contraseña",
          "OTP Verification": "Verificación OTP",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "Send OTP": "Enviar OTP",
          "An authentication code hase been sent to": "Se ha enviado un código de autenticación a",
          "Verification code": "Código de verificación",
          "Verify": "Verificar",
          "ADD": "AGREGAR",
          "Items": "Elementos",
          "Checkout": "Verificar",
          "hr": "hora",
          "Book Now": "Reservar ahora",
          "Buy Products": "Comprar productos",
          "Info": "Información",
          "Review": "Revisar",
          "Service Provided": "Servicio prestado",
          "Descriptions": "Descripciones",
          "Contact Detail": "Detalles del contacto",
          "Opps, Please Login or Register first!": "¡Opps, por favor inicie sesión o regístrese primero!",
          "Ongoing": "En curso",
          "Past": "Pasado",
          "Search Here": "Busca aquí",
          "Special Offer": "Oferta especial",
          "Categories": "Categorías",
          "See All": "Ver todo",
          "Recomended": "Recomendado",
          "Products": "productos",
          "Sign in": "Iniciar sesión",
          "Welcome Back!": "Bienvenido de nuevo!",
          "Email and phone Number": "Correo electrónico y número de teléfono",
          "Forgot Password?": "Has olvidado tu contraseña?",
          "Dont have an account?": "No tienes una cuenta?",
          "Register": "Registro",
          "Delivery Charge": "Gastos de envío",
          "Sold By": "Vendido por",
          "Highlight": "Destacar",
          "Disclaimer": "Descargo de responsabilidad",
          "Related Products": "Productos relacionados",
          "Images": "Imágenes",
          "My Order": "Mi pedido",
          "Order Details": "Detalles del pedido",
          "Order Status": "Estado del pedido",
          "Order Number": "Número de orden",
          "Your Order Status": "Estado de su pedido",
          "Share With Friends": "Compartir con amigos",
          "Invite Now": "invitar ahora",
          "Sign up": "Inscribirse",
          "Welcome": "Bienvenidos",
          "Email or phone number": "Correo electrónico o número de teléfono",
          "Referal Code (Optional)": "Código de referencia (opcional)",
          "Confirm Password": "Confirmar contraseña",
          "Alredy have an account?": "Ya tienes una cuenta?",
          "Add Service": "Agregar servicio",
          "Remove Service": "Eliminar servicio",
          "Duration": "Duración",
          "most rated": "más votados",
          "Sort": "Clasificar",
          "Filter": "Filtrar",
          "Please rate the quality of product for the order": "Califique la calidad del producto para el pedido.",
          "Get Started": "Empezar",
          "No Internet Connection": "Sin conexión a Internet",
          "Please wait": "Espere por favor",
          "Expiry": "Expiración",
          "Pay With Stripe": "Pagar con raya",
          "Book Service": "Reservar Servicio",
          "Back to Home": "De vuelta a casa",
          "All Transaction": "Todas las transacciones",
          "DEPOSIT": "DEPÓSITO",
          "WITHDRAW": "RETIRAR",
          "Welcome to Handyman": "Bienvenido a Manitas",
          "Continue with Email": "Continuar con correo electrónico",
          "Continue with Phone Number": "Continuar con número de teléfono",
          "My Account": "Mi cuenta",
          "All fields are required": "Todos los campos son obligatorios",
          "Could not determine your location": "No se pudo determinar su ubicación",
          "Successfully Added": "Agregado exitosamente",
          "Successfully Updated": "Actualizado exitosamente",
          "Card Information Saved": "Información de la tarjeta guardada",
          "Add Product Review": "Agregar revisión del producto",
          "Please add comments": "Por favor agregue comentarios",
          "Review Saved": "Reseña guardada",
          "Select Address": "Seleccionar dirección",
          "Appointment Detail": "Detalle de la cita",
          "COD": "contra reembolso",
          "Stripe": "Stripe",
          "PayPal": "Paypal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Created": "Creada",
          "Accepted": "Aceptado",
          "Rejected by Freelancer": "Rechazado por Freelancer",
          "Completed": "Terminado",
          "Cancelled": "Cancelado",
          "Refunded": "Reintegrado",
          "Delayed": "Demorado",
          "Status Updated": "Estado actualizado",
          "Please select Slot": "Por favor seleccione Tragamonedas",
          "Booking": "Reserva",
          "Sunday": "Domingo",
          "Monday": "Lunes",
          "Tuesday": "martes",
          "Wednesday": "miércoles",
          "Thursday": "jueves",
          "Friday": "Viernes",
          "Saturday": "sábado",
          "Please select payment method": "Por favor seleccione el método de pago",
          "Sorry we deliver the order near to": "Lo sentimos, entregamos el pedido cerca de",
          "Thank You!": "Gracias!",
          "For Your Order": "Para su pedido",
          "TRACK MY ORDER": "SEGUIMIENTO DE MI PEDIDO",
          "BACK TO HOME": "DE VUELTA A CASA",
          "Location services are disabled.": "Los servicios de ubicación están deshabilitados.",
          "Location permissions are denied": "Los permisos de ubicación están denegados",
          "Location permissions are permanently denied, we cannot request permissions.": "Los permisos de ubicación se niegan permanentemente, no podemos solicitar permisos.",
          "Select Coupon": "Seleccionar cupón",
          "Please select offer": "Por favor seleccione oferta",
          "update": "actualizar",
          "FAQ": "Preguntas más frecuentes",
          "Find Location": "Encontrar ubicacion",
          "Freelancer Products": "Productos para autónomos",
          "We already have product with other freelancer": "Ya tenemos producto con otro freelance",
          "Booking History": "Historial de reservas",
          "Inbox": "Bandeja de entrada",
          "Email is not valid": "El correo no es válido",
          "Notification": "Notificación",
          "Popular Product": "Producto Popular",
          "Product Category": "categoria de producto",
          "Product Checkout": "Pago del producto",
          "Product Detail": "Detalle del producto",
          "Something went wrong": "Algo salió mal",
          "password does not match": "las contraseñas no coinciden",
          "Service Detail": "Detalle del servicio",
          "Are you sure?": "Está seguro?",
          "Orders once placed cannot be cancelled and are non-refundable": "Los pedidos una vez realizados no se pueden cancelar y no son reembolsables",
          "Yes, Place Order": "Sí, realizar pedido",
          "Please select card": "Por favor, seleccione la tarjeta",
          "Creating Order": "Creando orden",
          "Track Booking": "Reserva de pista",
          "FAQs": "preguntas frecuentes",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy": "Política de privacidad",
          "to delete Address ?": "eliminar la dirección?",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.":
              "En publicaciones y diseño gráfico, lorem ipsum es un texto de relleno comúnmente utilizado para demostrar.",
          "Door to Door Supprot": "Soporte puerta a puerta",
          "Easy Track Order": "Orden de seguimiento fácil",
          "Appointment ID": "Identificación de cita",
          "Wallet Discount": "Descuento de billetera",
          "Apply Coupon Code": "Aplicar código de cupón",
          "Coupon Applied :": "Cupón aplicado:",
          "Available Balance": "Saldo disponible",
          "Complaints": "Quejas",
          "Issue With": "Problema con",
          "Freelancer": "Persona de libre dedicación",
          "Select Freelancer": "Seleccionar autónomo",
          "Select product": "Seleccionar producto",
          "Select service": "Seleccionar servicio",
          "Select Reason": "Seleccionar motivo",
          "Title": "Título",
          "Brief of your issue": "Resumen de su problema",
          "Comments": "Comentarios",
          "Write something on issue": "Escribe algo sobre el tema",
          "Upload Image": "Cargar imagen",
          "Full Name": "Nombre completo",
          "Message": "Mensaje",
          " - Valid until": " - Válido hasta",
          "Verify your phone number": "verifica tu numero de telefono",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y le enviaremos un código de verificación para generar una nueva contraseña",
          "Generate New Password": "Generar nueva contraseña",
          "New Password": "Nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "No Data Found": "Datos no encontrados",
          "No New Appointments Found": "No se encontraron nuevas citas",
          "No Ongoing Appointments Found": "No se encontraron citas en curso",
          "No Past Appointments Found": "No se encontraron citas pasadas",
          "No Data Found Near You!": "¡No se encontraron datos cerca de usted!",
          "Booking Cancel": "Reserva Cancelar",
          "Thank You! Your transaction is completed. tis is test": "¡Gracias! Su transacción está completa. esto es prueba",
          "No New Order Found": "No se encontró un nuevo pedido",
          "No Ongoing Order Found": "No se ha encontrado ningún pedido en curso",
          "No Past Order Found": "No se encontró ningún pedido anterior",
          "Order ID": "Solicitar ID",
          "Please enter valid details": "Por favor ingrese detalles válidos",
          "Handymans": "manitas",
          "Popularity": "Popularidad",
          "Price - Low to High": "Precios de barato a caro",
          "Price - Price High to Low": "Precio - Precio de mayor a menor",
          "A - Z": "A-Z",
          "Z - A": "Z-A",
          "Experience": "Experiencia",
          "Your Booking Code:": "Su código de reserva:",
          "All Transactions": "Todas las transacciones",
          "Panding Payment": "Pago pendiente",
          "Could not launch": "no se pudo iniciar",
          "Choose": "Elegir",
          "Chat": "Charlar",
          "Category": "Categoría",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "Es un hecho establecido desde hace mucho tiempo que un lector se distraerá con el contenido legible de una página cuando mire su diseño.",
          "The product arrived too late": "El producto llego demasiado tarde",
          "he product did not match the description": "El producto no coincidía con la descripción.",
          "The purchase was fraudulent": "La compra fue fraudulenta",
          "The product was damaged or defective": "El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item": "El comerciante envió el artículo equivocado",
          "Wrong Item Size or Wrong Product Shipped": "Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late": "El conductor llegó demasiado tarde",
          "Driver behavior": "Comportamiento del conductor",
          "Freelacer behavior": "Comportamiento del trabajador independiente",
          "Issue with Payment Amount": "Problema con el monto del pago",
          "Others": "Otros",
          "Freelancer arrived too late": "Freelancer llegó demasiado tarde",
          "Freelancer did not match the description": "Freelancer no coincide con la descripción",
          "Freelancer was fraudulent": "Freelancer era fraudulento",
          "Related to service": "Relacionado con el servicio",
          "Satisfaction of services": "Satisfacción de servicios",
          "Choose Issue With": "Elija Problema con",
          "Choose Reason": "Elija la razón",
          "Choose Service": "Elija el servicio",
          "Choose Product": "Elija Producto",
          "Complaints registered": "Quejas registradas",
          "We have received your request, we will respond on your issue soon": "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "Contact Information Sent": "Información de contacto enviada",
          "Alert!": "¡Alerta!",
          "Okay": "De acuerdo",
          "Edit Profile": "Editar perfil",
          "Something went wrong while signup": "Algo salió mal durante el registro",
          "error": "error",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado el código de verificación el",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza",
          "Access denied": "Acceso denegado",
          "Phone Number is required": "Se requiere número de teléfono",
          "Product Order History": "Historial de pedidos de productos",
          "Product Listing": "Listado de productos",
          "Product Order Detail": "Detalle del pedido del producto",
          "Your friend": "Tu amigo",
          "has invited you to": "te ha invitado a",
          "Hey Buddy download": "Hola amigo descargar",
          "rom app store and use my code": "tienda de aplicaciones rom y usa mi código",
          "Share with buddies": "compartir con amigos",
          "while sign up we both will get": "mientras te registras ambos conseguiremos",
          "wallet amount": "monto de la billetera",
          "Copied to clipboard": "Copiado al portapapeles",
          "Use this code for verification": "Utilice este código para la verificación",
          "Don't share this otp to anybody else": "No compartas este otp con nadie más.",
          "phone verification": "verificación telefónica",
          "Getting Rewards": "Obtener recompensas",
          "Congratulations your friend have received the": "Enhorabuena, tu amigo ha recibido el",
          "Congratulations you have received the": "Felicidades has recibido el",
          "Congratulations you & your friend have received the": "Felicitaciones, usted y su amigo han recibido el",
          "Congratulation": "Felicitaciones",
          "Close": "Cerca",
          "Ok": "OK",
          "Price L-H": "Precio L-H",
          "Price H-L": "Precio H-L",
          "A-Z": "ARIZONA",
          "Z-A": "Z-A",
          "Single Product Review": "Revisión de un solo producto",
          "Subcategory": "Subcategoría",
          "Top Freelancers": "Mejores autónomos",
          "Top Products": "Productos principales",
          "Service Appointments": "Citas de servicio",
          "Product Orders": "Pedidos de productos",
          "Profile": "Perfil",
          "About Us": "Sobre nosotros",
          "Connection failed!": "¡La conexión falló!",
          "Warning": "Advertencia",
          "Clear Cart": "Vaciar carrito",
          "You already have item's in cart with different grocery store": "Ya tienes artículos en el carrito con otra tienda de comestibles",
          "Session expired!": "¡Sesión expirada!",
          "History": "Historia",
          "Shop": "Comercio",
          "Account": "Cuenta",
          "Confirm Location": "Confirmar ubicación",
          "Use My Current Location": "Usar mi ubicación actual",
          "Featching Location": "Obtener ubicación",
          "We already have service in cart with another freelancer": "Ya tenemos servicio en carrito con otro autónomo"
        },
        "ar_AE": {
          "Edit": "يحرر",
          "Product History": "تاريخ المنتج",
          "Favorite": "مفضل",
          "Language": "لغة",
          "Popular": "جمع",
          "Change Password": "غير كلمة السر",
          "Contact Us": "اتصل بنا",
          "Chats": "الدردشات",
          "Help": "مساعدة",
          "Your Address": "عنوانك",
          "Wallet": "محفظة",
          "Refer & Earn": "قم بالإحالة واكسب",
          "About us": "معلومات عنا",
          "Logout": "تسجيل خروج",
          "Login / Register": "دخولتسجيل",
          "New": "جديد",
          "Add New Address": "أضف عنوان جديد",
          "Update Address": "تحديث العنوان",
          "Address": "تبوك",
          "House / Flat No": "منزل / شقة لا",
          "Landmark": "معلم معروف",
          "Zipcode": "الرمز البريدي",
          "SAVE AS": "حفظ باسم",
          "Home": "مسكن",
          "Work": "عمل",
          "Other": "آخر",
          "Submit": "يُقدِّم",
          "Update": "تحديث",
          "Add New Card": "إضافة بطاقة جديدة",
          "Email Address": "عنوان البريد الالكترونى",
          "Card Holder Name": "إسم صاحب البطاقة",
          "Card Number": "رقم البطاقة",
          "CVV": "CVV",
          "MM/YY": "شهر / سنة",
          "ADD CARD": "إضافة بطاقة",
          "Please rate the quality of service for the order": "يرجى تقييم جودة الخدمة للطلب",
          "Your comments and suggesstions help us improve the service quality better!": "تساعدنا تعليقاتك واقتراحاتك على تحسين جودة الخدمة بشكل أفضل!",
          "Write Notes": "اكتب الملاحظات",
          "Add Review": "إضافة مراجعة",
          "Save": "يحفظ",
          "Cancle": "إلغاء",
          "Add+": "أضف +",
          "Are you sure": "هل أنت واثق",
          "To delete Address ?": "لحذف العنوان؟",
          "Cancel": "يلغي",
          "Delete": "حذف",
          "year experience": "سنة خبرة",
          "My Appointment": "تعييني",
          "Item Total": "مجموع الاشياء",
          "Item discount": "خصم البند",
          "Distance Charge": "المسافة تهمة",
          "Taxes and Charges": "الضرائب والرسوم",
          "Grand Total": "المبلغ الإجمالي",
          "Booking Details": "تفاصيل الحجز",
          "Appointment Number": "رقم الموعد",
          "Payment": "دفع",
          "Your Appoinments Status": "حالة المواعيد الخاصة بك",
          "Select date of service": "حدد تاريخ الخدمة",
          "No Slots Found": "لم يتم العثور على فتحات",
          "Time to start service": "حان الوقت لبدء الخدمة",
          "to": "إلى",
          "Chekout": "تشيكوت",
          "Message...": "رسالة...",
          "min duration": "مدة دقيقة",
          "View": "رأي",
          "Notes for service": "ملاحظات للخدمة",
          "Offers & Benefits": "العروض والمزايا",
          "Apply Coupon": "تطبيق القسيمة",
          "Apply Wallet Coin": "تطبيق Wallet Coin",
          "Bill Details": "تفاصيل الفاتورة",
          "To Pay": "للدفع",
          "Payment Method": "طريقة الدفع او السداد",
          "Please Add Your Address": "الرجاء إضافة العنوان الخاص بك",
          "Pay": "يدفع",
          "Access Your": "الوصول الخاص بك",
          "Location": "موقع",
          "Use Current Location": "استخدام الموقع الحالي",
          "Choose Location": "اختيار موقع",
          "Password": "كلمة المرور",
          "Login": "تسجيل الدخول",
          "Use coupon code": "استخدم رمز القسيمة",
          "- Valid until": "- صالح حتى",
          "Apply": "يتقدم",
          "Choose From": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Gender": "جنس",
          "Male": "ذكر",
          "Female": "أنثى",
          "Email": "البريد الإلكتروني",
          "Search": "يبحث",
          "Start typing to search": "ابدأ الكتابة للبحث",
          "Code": "شفرة",
          "Phone": "هاتف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "تعذر الاتصال بالشبكة",
          "Please check and try again.": "يرجى مراجعة وحاول مرة أخرى.",
          "retry": "أعد المحاولة",
          "Chat with us": "دردش معنا",
          "Search location": "موقع البحث",
          "USE MY CURRENT LOCATION": "استخدم موقعي الحالي",
          "Forgot Passwrord": "نسيت كلمة المرور",
          "OTP Verification": "التحقق من OTP",
          "Please enter your credentials": "الرجاء إدخال بيانات الاعتماد الخاصة بك",
          "Send OTP": "أرسل OTP",
          "An authentication code hase been sent to": "تم إرسال رمز المصادقة إلى",
          "Verification code": "رمز التحقق",
          "Verify": "يؤكد",
          "ADD": "يضيف",
          "Items": "العناصر",
          "Checkout": "الدفع",
          "hr": "ساعة",
          "Book Now": "احجز الآن",
          "Buy Products": "شراء المنتجات",
          "Info": "معلومات",
          "Review": "إعادة النظر",
          "Service Provided": "تم توفير الخدمة",
          "Descriptions": "الأوصاف",
          "Contact Detail": "تفاصيل الإتصال",
          "Opps, Please Login or Register first!": "عفوا ، الرجاء تسجيل الدخول أو التسجيل أولا!",
          "Ongoing": "جاري التنفيذ",
          "Past": "ماضي",
          "Search Here": "ابحث هنا",
          "Special Offer": "عرض خاص",
          "Categories": "فئات",
          "See All": "اظهار الكل",
          "Recomended": "موصى به",
          "Products": "منتجات",
          "Sign in": "تسجيل الدخول",
          "Welcome Back!": "مرحبًا بعودتك!",
          "Email and phone Number": "البريد الإلكتروني ورقم الهاتف",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Dont have an account?": "ليس لديك حساب؟",
          "Register": "يسجل",
          "Delivery Charge": "رسوم التوصيل",
          "Sold By": "تم بيعها من قبل",
          "Highlight": "تسليط الضوء",
          "Disclaimer": "تنصل",
          "Related Products": "منتجات ذات صله",
          "Images": "الصور",
          "My Order": "طلبي",
          "Order Details": "تفاصيل الطلب",
          "Order Status": "حالة الطلب",
          "Order Number": "رقم الطلب",
          "Your Order Status": "حالة طلبك",
          "Share With Friends": "شارك مع الاصدقاء",
          "Invite Now": "ادعُ الآن",
          "Sign up": "اشتراك",
          "Welcome": "أهلا وسهلا",
          "Email or phone number": "البريد الإلكتروني أو رقم الهاتف",
          "Referal Code (Optional)": "كود الإحالة (اختياري)",
          "Confirm Password": "تأكيد كلمة المرور",
          "Alredy have an account?": "الريدي لديك حساب؟",
          "Add Service": "أضف خدمة",
          "Remove Service": "إزالة الخدمة",
          "Duration": "مدة",
          "most rated": "الأكثر تقييما",
          "Sort": "فرز",
          "Filter": "منقي",
          "Please rate the quality of product for the order": "يرجى تقييم جودة المنتج للطلب",
          "Get Started": "البدء",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Please wait": "أرجو الإنتظار",
          "Expiry": "انقضاء",
          "Pay With Stripe": "الدفع باستخدام Stripe",
          "Book Service": "خدمة الكتاب",
          "Back to Home": "العودة إلى المنزل",
          "All Transaction": "كل المعاملات",
          "DEPOSIT": "الوديعة",
          "WITHDRAW": "ينسحب",
          "Welcome to Handyman": "مرحبا بكم في Handyman",
          "Continue with Email": "تواصل مع البريد الإلكتروني",
          "Continue with Phone Number": "تواصل مع رقم الهاتف",
          "My Account": "حسابي",
          "All fields are required": "جميع الحقول مطلوبة",
          "Could not determine your location": "تعذر تحديد موقعك",
          "Successfully Added": "أضيف بنجاح",
          "Successfully Updated": "تم التحديث بنجاح",
          "Card Information Saved": "تم حفظ معلومات البطاقة",
          "Add Product Review": "إضافة مراجعة المنتج",
          "Please add comments": "الرجاء إضافة التعليقات",
          "Review Saved": "تم حفظ المراجعة",
          "Select Address": "حدد العنوان",
          "Appointment Detail": "تفاصيل الموعد",
          "COD": "الدفع عند الاستلام",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Created": "مخلوق",
          "Accepted": "وافقت",
          "Rejected by Freelancer": "مرفوض من قبل فريلانسر",
          "Completed": "مكتمل",
          "Cancelled": "ألغيت",
          "Refunded": "معاد",
          "Delayed": "تأخير",
          "Status Updated": "تم تحديث الحالة",
          "Please select Slot": "يرجى تحديد Slot",
          "Booking": "الحجز",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "يوم الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "يوم الخميس",
          "Friday": "جمعة",
          "Saturday": "السبت",
          "Please select payment method": "الرجاء تحديد طريقة الدفع",
          "Sorry we deliver the order near to": "نأسف لتسليم الطلب بالقرب من",
          "Thank You!": "شكرا لك!",
          "For Your Order": "لطلبك",
          "TRACK MY ORDER": "تابع طلبي",
          "BACK TO HOME": "العودة إلى المنزل",
          "Location services are disabled.": "خدمات الموقع معطلة.",
          "Location permissions are denied": "تم رفض أذونات الموقع",
          "Location permissions are permanently denied, we cannot request permissions.": "أذونات الموقع مرفوضة بشكل دائم ، ولا يمكننا طلب أذونات.",
          "Select Coupon": "حدد القسيمة",
          "Please select offer": "الرجاء تحديد عرض",
          "update": "تحديث",
          "FAQ": "التعليمات",
          "Find Location": "البحث عن الموقع",
          "Freelancer Products": "منتجات Freelancer",
          "We already have product with other freelancer": "لدينا بالفعل منتج مع المستقل الآخر",
          "Booking History": "سجل الحجز",
          "Inbox": "صندوق الوارد",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Notification": "تنبيه",
          "Popular Product": "منتج شعبي",
          "Product Category": "فئة المنتج",
          "Product Checkout": "المنتج الخروج",
          "Product Detail": "تفاصيل المنتج",
          "Something went wrong": "هناك خطأ ما",
          "password does not match": "كلمة السر غير متطابقة",
          "Service Detail": "تفاصيل الخدمة",
          "Are you sure?": "هل أنت واثق؟",
          "Orders once placed cannot be cancelled and are non-refundable": "الطلبات بمجرد تقديمها لا يمكن إلغاؤها وغير قابلة للاسترداد",
          "Yes, Place Order": "نعم ، ضع الطلب",
          "Please select card": "الرجاء تحديد البطاقة",
          "Creating Order": "ترتيب إنشاء",
          "Track Booking": "تتبع الحجز",
          "FAQs": "أسئلة وأجوبة",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Terms & Conditions": "البنود و الظروف",
          "Privacy Policy": "سياسة الخصوصية",
          "to delete Address ?": "لحذف العنوان؟",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.": "في النشر والتصميم الجرافيكي ، يعد lorem ipsum نصًا حشوًا يشيع استخدامه للتوضيح.",
          "Door to Door Supprot": "دعم من الباب الى الباب",
          "Easy Track Order": "ترتيب سهل التعقب",
          "Appointment ID": "معرف الموعد",
          "Wallet Discount": "خصم المحفظة",
          "Apply Coupon Code": "تطبيق رمز القسيمة",
          "Coupon Applied :": "القسيمة المطبقة:",
          "Available Balance": "الرصيد المتوفر",
          "Complaints": "شكاوي",
          "Issue With": "القضية مع",
          "Freelancer": "مستقل",
          "Select Freelancer": "حدد Freelancer",
          "Select product": "حدد المنتج",
          "Select service": "اختر الخدمة",
          "Select Reason": "حدد السبب",
          "Title": "عنوان",
          "Brief of your issue": "موجز عن مشكلتك",
          "Comments": "تعليقات",
          "Write something on issue": "اكتب شيئًا عن القضية",
          "Upload Image": "تحميل الصور",
          "Full Name": "الاسم الكامل",
          "Message": "رسالة",
          " - Valid until": " - صالح حتى",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز تحقق لإنشاء كلمة مرور جديدة",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Update Password": "تطوير كلمة السر",
          "No Data Found": "لاتوجد بيانات",
          "No New Appointments Found": "لم يتم العثور على مواعيد جديدة",
          "No Ongoing Appointments Found": "لم يتم العثور على مواعيد جارية",
          "No Past Appointments Found": "لم يتم العثور على مواعيد سابقة",
          "No Data Found Near You!": "لا توجد بيانات بالقرب منك!",
          "Booking Cancel": "إلغاء الحجز",
          "Thank You! Your transaction is completed. tis is test": "شكرا لك! اكتملت معاملتك. هذا هو الاختبار",
          "No New Order Found": "لم يتم العثور على طلب جديد",
          "No Ongoing Order Found": "لم يتم العثور على طلب جاري",
          "No Past Order Found": "لم يتم العثور على طلب سابق",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Please enter valid details": "الرجاء إدخال تفاصيل صحيحة",
          "Handymans": "الماهرون",
          "Popularity": "شعبية",
          "Price - Low to High": "السعر من الارخص للاعلى",
          "Price - Price High to Low": "السعر - السعر الأعلى إلى الأدنى",
          "A - Z": "أ - ي",
          "Z - A": "ض - أ",
          "Experience": "خبرة",
          "Your Booking Code:": "رمز الحجز الخاص بك:",
          "All Transactions": "كل الحركات المالية",
          "Panding Payment": "دفع Panding",
          "Could not launch": "تعذر الإطلاق",
          "Choose": "يختار",
          "Chat": "دردشة",
          "Category": "فئة",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.":
              "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها.",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "he product did not match the description": "لم يتطابق المنتج مع الوصف",
          "The purchase was fraudulent": "كان الشراء احتياليًا",
          "The product was damaged or defective": "المنتج تالف أو به عيب",
          "The merchant shipped the wrong item": "التاجر شحن السلعة الخاطئة",
          "Wrong Item Size or Wrong Product Shipped": "حجم السلعة غير صحيح أو شحن منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Freelacer behavior": "سلوك العمل بالقطعة",
          "Issue with Payment Amount": "مشكلة في مبلغ الدفع",
          "Others": "آحرون",
          "Freelancer arrived too late": "وصل المستقل بعد فوات الأوان",
          "Freelancer did not match the description": "مترجم مستقل لا يتطابق مع الوصف",
          "Freelancer was fraudulent": "كان العامل المستقل محتالاً",
          "Related to service": "ذات الصلة بالخدمة",
          "Satisfaction of services": "الرضا عن الخدمات",
          "Choose Issue With": "اختر المشكلة مع",
          "Choose Reason": "اختر السبب",
          "Choose Service": "اختر الخدمة",
          "Choose Product": "اختر المنتج",
          "Complaints registered": "تم تسجيل الشكاوى",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "Alert!": "انذار!",
          "Okay": "تمام",
          "Edit Profile": "تعديل الملف الشخصي",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "error": "خطأ",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Password Updated": "تم تحديث كلمة السر",
          "Access denied": "تم الرفض",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Product Order History": "تاريخ طلب المنتج",
          "Product Listing": "قائمة المنتجات",
          "Product Order Detail": "تفاصيل طلب المنتج",
          "Your friend": "صديقك",
          "has invited you to": "دعاك إلى",
          "Hey Buddy download": "يا صديقي تنزيل",
          "rom app store and use my code": "rom app store واستخدم الكود الخاص بي",
          "Share with buddies": "شارك مع الأصدقاء",
          "while sign up we both will get": "أثناء التسجيل سيحصل كلانا",
          "wallet amount": "مبلغ المحفظة",
          "Copied to clipboard": "نسخ إلى الحافظة",
          "Use this code for verification": "استخدم هذا الرمز للتحقق",
          "Don't share this otp to anybody else": "لا تشارك هذا otp مع أي شخص آخر",
          "phone verification": "التحقق من الهاتف",
          "Getting Rewards": "الحصول على المكافآت",
          "Congratulations your friend have received the": "مبروك لقد تلقى صديقك",
          "Congratulations you have received the": "تهانينا ، لقد تلقيت",
          "Congratulations you & your friend have received the": "تهانينا ، لقد تلقيت أنت وصديقك",
          "Congratulation": "تهنئة",
          "Close": "قريب",
          "Ok": "موافق",
          "Price L-H": "السعر L-H",
          "Price H-L": "السعر H-L",
          "A-Z": "من الألف إلى الياء",
          "Z-A": "Z-A",
          "Single Product Review": "مراجعة منتج واحد",
          "Subcategory": "تصنيف فرعي",
          "Top Freelancers": "كبار العاملين لحسابهم الخاص",
          "Top Products": "أهم المنتجات",
          "Service Appointments": "مواعيد الخدمة",
          "Product Orders": "طلبات المنتج",
          "Profile": "الملف الشخصي",
          "About Us": "معلومات عنا",
          "Connection failed!": "فشل الاتصال!",
          "Warning": "تحذير",
          "Clear Cart": "مسح السلة",
          "You already have item's in cart with different grocery store": "لديك بالفعل عنصر في سلة التسوق مع متجر بقالة مختلف",
          "Session expired!": "انتهت الجلسة!",
          "History": "تاريخ",
          "Shop": "محل",
          "Account": "الحساب",
          "Confirm Location": "قم بتأكيد الموقع",
          "Use My Current Location": "استخدم موقعي الحالي",
          "Featching Location": "إحضار الموقع",
          "We already have service in cart with another freelancer": "لدينا بالفعل خدمة في عربة التسوق مع موظف مستقل آخر"
        },
      };
}
