/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Handy Service Full App Flutter V3
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Edit": "Edit",
          "My Services": "My Services",
          "My Products": "My Products",
          "My Slot": "My Slot",
          "Review": "Review",
          "Language": "Language",
          "Change Password": "Change Password",
          "Contact Us": "Contact Us",
          "Chats": "Chats",
          "Help": "Help",
          "About us": "About us",
          "Logout": "Logout",
          "new": "new",
          "Add New Product": "Add New Product",
          "Update Product": "Update Product",
          "Choose From": "Choose From",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Cancel": "Cancel",
          "product Name": "product Name",
          "Select Category": "Select Category",
          "Select": "Select",
          "Select Sub Category": "Select Sub Category",
          "Product price": "Product price",
          "Discount": "Discount",
          "Sell price": "Sell price",
          "Description": "Description",
          "Status": "Status",
          "Active": "Active",
          "Hide": "Hide",
          "Available": "Available",
          "In Stock": "In Stock",
          "Out of Stock": "Out of Stock",
          "Is Single": "Is Single",
          "In Offer": "In Offer",
          "Add Photos": "Add Photos",
          "In Gram": "In Gram",
          "Gram Value": "Gram Value",
          "In KG": "In KG",
          "KG Value": "KG Value",
          "In Liter": "In Liter",
          "Liter Value": "Liter Value",
          "In PCs": "In PCs",
          "PCs Value": "PCs Value",
          "In ML": "In ML",
          "ML Value": "ML Value",
          "Key Features": "Key Features",
          "Disclaimer": "Disclaimer",
          "Submit": "Submit",
          "Add New Service": "Add New Service",
          "Update Service": "Update Service",
          "Service Name": "Service Name",
          "Service price": "Service price",
          "Add New Slot": "Add New Slot",
          "Update Slot": "Update Slot",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Open Time": "Open Time",
          "Close Time": "Close Time",
          "to": "to",
          "Are you sure": "Are you sure",
          "to delete this slot ?": "to delete this slot ?",
          "Delete": "Delete",
          "Add Slot": "Add Slot",
          "Services": "Services",
          "Total Earning": "Total Earning",
          "Total Service": "Total Service",
          "Upcoming Services": "Upcoming Services",
          "Todays Service": "Todays Service",
          "Products": "Products",
          "Total Product": "Total Product",
          "Upcoming Products": "Upcoming Products",
          "Todays Product": "Todays Product",
          "Chart": "Chart",
          "Message...": "Message...",
          "Save": "Save",
          "Cancle": "Cancle",
          "Email or phone number": "Email or phone number",
          "Password": "Password",
          "Login": "Login",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Male": "Male",
          "Gender": "Gender",
          "Female": "Female",
          "Email": "Email",
          "Code": "Code",
          "Phone": "Phone",
          "Freelancing Details": "Freelancing Details",
          "Hourly Price": "Hourly Price",
          "Total Experience": "Total Experience",
          "Have Shop?": "Have Shop?",
          "City ID": "City ID",
          "Zip Code": "Zip Code",
          "Latitude": "Latitude",
          "Longitude": "Longitude",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again": "Please check and try again",
          "retry": "retry",
          "Verify": "Verify",
          "Verification code": "Verification code",
          "An authentication code hase been sent to": "An authentication code hase been sent to",
          "OTP Verification": "OTP Verification",
          "Send OTP": "Send OTP",
          "Email Address": "Email Address",
          "Please enter your credentials": "Please enter your credentials",
          "Forgot Password": "Forgot Password",
          "New": "New",
          "Ongoing": "Ongoing",
          "Past": "Past",
          "Sign in": "Sign in",
          "Welcome Back!": "Welcome Back!",
          "Order Details": "Order Details",
          "Order Number": "Order Number",
          "Payment": "Payment",
          "Orders": "Orders",
          "Item Total": "Item Total",
          "Item discount": "Item discount",
          "Delivery Charge": "Delivery Charge",
          "Taxes and Charges": "Taxes and Charges",
          "Grand Total": "Grand Total",
          "Your Appoinments Status": "Your Appoinments Status",
          "Your Order Status": "Your Order Status",
          "Accept": "Accept",
          "Decline": "Decline",
          "Update Status": "Update Status",
          "ORDER": "ORDER",
          "Add+": "Add+",
          "edit": "edit",
          "Distance Charge": "Distance Charge",
          "Appointment Detail": "Appointment Detail",
          "Appointment Number": "Appointment Number",
          "Booking Details": "Booking Details",
          "Get Started": "Get Started",
          "to delete Slots ?": "to delete Slots ?",
          "Please wait": "Please wait",
          "No Internet Connection": "No Internet Connection",
          "Continue with Phone Number": "Continue with Phone Number",
          "Continue with Email": "Continue with Email",
          "Welcome to Handyman": "Welcome to Handyman",
          "My Account": "My Account",
          "Add Product": "Add Product",
          "Please select category first": "Please select category first",
          "All fields are required": "All fields are required",
          "Addded": "Addded",
          "update": "update",
          "Discount must be less than 100": "Discount must be less than 100",
          "Add Service": "Add Service",
          "Slots are empty": "Slots are empty",
          "Already exist": "Already exist",
          "Please select time": "Please select time",
          "Analyze": "Analyze",
          "Chat": "Chat",
          "Select City": "Select City",
          "Edit Profile": "Edit Profile",
          "Home": "Home",
          "Created": "Created",
          "Accepted": "Accepted",
          "Completed": "Completed",
          "Rejected": "Rejected",
          "Cancelled": "Cancelled",
          "Refunded": "Refunded",
          "Delayed": "Delayed",
          "Inbox": "Inbox",
          "Email is not valid": "Email is not valid",
          "Notification": "Notification",
          "Product Category": "Product Category",
          "Product Order History": "Product Order History",
          "Product Order Detail": "Product Order Detail",
          "Work": "Work",
          "Others": "Others",
          "Status Updated": "Status Updated",
          "Product Sub Category": "Product Sub Category",
          "Reviews": "Reviews",
          "Served Category": "Served Category",
          "Select Service Category": "Select Service Category",
          "Service": "Service",
          "Service Detail": "Service Detail",
          "My Slots": "My Slots",
          "Slot Remove Successfully": "Slot Remove Successfully",
          "Analytics": "Analytics",
          "Profile": "Profile",
          "Welcome to Handyman Freelancer": "Welcome to Handyman Freelancer",
          "Door to Door Supprot": "Door to Door Supprot",
          "Easy Track Order": "Easy Track Order",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.": "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.",
          "Partner with Us": "Partner with Us",
          "Confirm Password": "Confirm Password",
          "Experience in year": "Experience in year",
          "Select Latitude & Longitude from here :": "Select Latitude & Longitude from here :",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "Please enter valid Latitude & Longitude otherwise app may not work properly.",
          "Your Latitude": "Your Latitude",
          "Your Longitude": "Your Longitude",
          "Sign up": "Sign up",
          "Alredy have an account?": "Alredy have an account?",
          "Phone number is required": "Phone number is required",
          "Something went wrong while signup": "Something went wrong while signup",
          "message": "message",
          "Something went wrong": "Something went wrong",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Your Email is Verified": "Your Email is Verified",
          "Please verify email": "Please verify email",
          "Please verify phone number": "Please verify phone number",
          "Please upload your cover photo": "Please upload your cover photo",
          "password does not match": "password does not match",
          "Success!": "Success!",
          "Your Request is submitted": "Your Request is submitted",
          "Okay": "Okay",
          "Could not launch": "Could not launch",
          "Verified": "Verified",
          "Search": "Search",
          "Start typing to search": "Start typing to search",
          "Zipcode": "Zipcode",
          "Email or phone Number": "Email or phone Number",
          "Forgot Password?": "Forgot Password?",
          "Phone Number": "Phone Number",
          "Register": "Register",
          "Access denied": "Access denied",
          "Phone Number is required": "Phone Number is required",
          "Product Review": "Product Review",
          "About Us": "About Us",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "FAQs": "FAQs",
          "Terms & Conditions": "Terms & Conditions",
          "Privacy Policy": "Privacy Policy",
          "Product Name": "Product Name",
          "Daily": "Daily",
          "Monthly": "Monthly",
          "Yearly": "Yearly",
          "Appointment": "Appointment",
          "Products Order": "Products Order",
          "Earnings": "Earnings",
          "Total": "Total",
          "Average": "Average",
          "Day": "Day",
          "Bookings": "Bookings",
          "Months": "Months",
          "Total number of bookings": "Total number of bookings",
          "Total number of orders": "Total number of orders",
          "Full Name": "Full Name",
          "Message": "Message",
          "camera": "camera",
          "Verify your phone number": "Verify your phone number",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Enter your email address or phone number and we will send a verification code to generate a new password",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Update Password": "Update Password",
          "No Ongoing Appointments Found": "No Ongoing Appointments Found",
          "No Old Appointments Found": "No Old Appointments Found",
          "No New Orders Found": "No New Orders Found",
          "No Ongoing Orders Found": "No Ongoing Orders Found",
          "No Old Orders Found": "No Old Orders Found",
          "No Data Found": "No Data Found",
          "January": "January",
          "February": "February",
          "March": "March",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "April": "April",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "Password mismatch": "Password mismatch",
          "Password Updated": "Password Updated",
          "Fetching...": "Fetching...",
          "Refreshing...": "Refreshing...",
          "Yes Delete": "Yes Delete",
          "Are you sure?": "Are you sure?",
          "To delete this product": "To delete this product",
          "Yes Update": "Yes Update",
          "Change the status of this product": "Change the status of this product",
          "Panding Payment": "Panding Payment",
          "Product Reviews": "Product Reviews",
          "To delete this service": "To delete this service",
          "Change the status of this service": "Change the status of this service",
          "Session expired!": "Session expired!",
        },
        'hi_IN': {
          "Edit": "संपादन",
          "My Services": "मेरी सेवाएं",
          "My Products": "मेरे उत्पाद",
          "My Slot": "मेरा स्लॉट",
          "Review": "समीक्षा",
          "Language": "भाषा",
          "Change Password": "पासवर्ड बदलें",
          "Contact Us": "संपर्क करें",
          "Chats": "चैट",
          "Help": "मदद करना",
          "About us": "हमारे बारे में",
          "Logout": "लॉग आउट",
          "new": "नया",
          "Add New Product": "नया उत्पाद जोड़ें",
          "Update Product": "उत्पाद अपडेट करें",
          "Choose From": "से चुनें",
          "Camera": "कैमरा",
          "Gallery": "गेलरी",
          "Cancel": "रद्द करना",
          "product Name": "प्रोडक्ट का नाम",
          "Select Category": "श्रेणी चुनना",
          "Select": "चुनना",
          "Select Sub Category": "उप श्रेणी का चयन करें",
          "Product price": "उत्पाद की कीमत",
          "Discount": "छूट",
          "Sell price": "विक्रय मूल्य",
          "Description": "विवरण",
          "Status": "दर्जा",
          "Active": "सक्रिय",
          "Hide": "छिपाना",
          "Available": "उपलब्ध",
          "In Stock": "स्टॉक में",
          "Out of Stock": "स्टॉक ख़त्म",
          "Is Single": "अकेला है",
          "In Offer": "प्रस्ताव में",
          "Add Photos": "तस्वीरें जोडो",
          "In Gram": "ग्राम में",
          "Gram Value": "ग्राम मूल्य",
          "In KG": "केजी . में",
          "KG Value": "केजी मूल्य",
          "In Liter": "लीटर में",
          "Liter Value": "लीटर मूल्य",
          "In PCs": "टुकड़े में",
          "PCs Value": "टुकड़ा मूल्य",
          "In ML": "एमएल . में",
          "ML Value": "एमएल मूल्य",
          "Key Features": "प्रमुख विशेषताऐं",
          "Disclaimer": "अस्वीकरण",
          "Submit": "प्रस्तुत करना",
          "Add New Service": "नई सेवा जोड़ें",
          "Update Service": "अद्यतन सेवा",
          "Service Name": "सेवा का नाम",
          "Service price": "सेवा मूल्य",
          "Add New Slot": "नया स्लॉट जोड़ें",
          "Update Slot": "स्लॉट अपडेट करें",
          "Sunday": "रविवार",
          "Monday": "सोमवार",
          "Tuesday": "मंगलवार",
          "Wednesday": "बुधवार",
          "Thursday": "गुरुवार",
          "Friday": "शुक्रवार",
          "Saturday": "शनिवार",
          "Open Time": "खुला समय",
          "Close Time": "बंद होने का समय",
          "to": "प्रति",
          "Are you sure": "क्या आपको यकीन है",
          "to delete this slot ?": "इस स्लॉट को हटाने के लिए?",
          "Delete": "मिटाना",
          "Add Slot": "स्लॉट जोड़ें",
          "Services": "सेवाएं",
          "Total Earning": "कुल कमाई",
          "Total Service": "कुल सेवा",
          "Upcoming Services": "आगामी सेवाएं",
          "Todays Service": "आज की सेवा",
          "Products": "उत्पादों",
          "Total Product": "कुल उत्पाद",
          "Upcoming Products": "आगामी उत्पाद",
          "Todays Product": "आज का उत्पाद",
          "Chart": "चार्ट",
          "Message...": "संदेश...",
          "Save": "बचाना",
          "Cancle": "कैंक्ल",
          "Email or phone number": "ईमेल या फोन नंबर",
          "Password": "पासवर्ड",
          "Login": "लॉग इन करें",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Male": "पुरुष",
          "Gender": "लिंग",
          "Female": "मादा",
          "Email": "ईमेल",
          "Code": "कोड",
          "Phone": "फ़ोन",
          "Freelancing Details": "फ्रीलांसिंग विवरण",
          "Hourly Price": "प्रति घंटा मूल्य",
          "Total Experience": "कुल अनुभव",
          "Have Shop?": "दुकान है?",
          "City ID": "सिटी आईडी",
          "Zip Code": "पिन कोड",
          "Latitude": "अक्षांश",
          "Longitude": "देशान्तर",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again": "कृपया जाँच करें और पुनः प्रयास करें",
          "retry": "पुन: प्रयास करें",
          "Verify": "सत्यापित करना",
          "Verification code": "पुष्टि संख्या",
          "An authentication code hase been sent to": "एक प्रमाणीकरण कोड भेजा गया है",
          "OTP Verification": "ओटीपी सत्यापन",
          "Send OTP": "OTP भेजें",
          "Email Address": "ईमेल पता",
          "Please enter your credentials": "कृपया अपनी साख दर्ज करें",
          "Forgot Password": "पासवर्ड भूल गए",
          "New": "नया",
          "Ongoing": "चल रहे",
          "Past": "अतीत",
          "Sign in": "साइन इन करें",
          "Welcome Back!": "वापसी पर स्वागत है!",
          "Order Details": "ऑर्डर का विवरण",
          "Order Number": "क्रम संख्या",
          "Payment": "भुगतान",
          "Orders": "आदेश",
          "Item Total": "आइटम का कुल",
          "Item discount": "आइटम छूट",
          "Delivery Charge": "डिलीवरी चार्ज",
          "Taxes and Charges": "कर और शुल्क",
          "Grand Total": "कुल योग",
          "Your Appoinments Status": "आपकी नियुक्तियों की स्थिति",
          "Your Order Status": "आपके आदेश की स्थिति",
          "Accept": "स्वीकार करना",
          "Decline": "पतन",
          "Update Status": "नवीनतम स्थिति",
          "ORDER": "गण",
          "Add+": "जोड़ें+",
          "edit": "संपादन",
          "Distance Charge": "दूरी प्रभार",
          "Appointment Detail": "नियुक्ति विवरण",
          "Appointment Number": "नियुक्ति संख्या",
          "Booking Details": "बुकिंग विवरण",
          "Get Started": "शुरू हो जाओ",
          "to delete Slots ?": "स्लॉट हटाने के लिए?",
          "Please wait": "कृपया प्रतीक्षा करें",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Continue with Phone Number": "फ़ोन नंबर के साथ जारी रखें",
          "Continue with Email": "ईमेल के साथ जारी रखें",
          "Welcome to Handyman": "अप्रेंटिस में आपका स्वागत है",
          "My Account": "मेरा खाता",
          "Add Product": "उत्पाद जोड़ें",
          "Please select category first": "कृपया पहले श्रेणी का चयन करें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Addded": "जोड़ा गया",
          "update": "अपडेट करें",
          "Discount must be less than 100": "छूट 100 . से कम होनी चाहिए",
          "Add Service": "सेवा जोड़ें",
          "Slots are empty": "स्लॉट खाली हैं",
          "Already exist": "पहले से ही मौजूद",
          "Please select time": "कृपया समय चुनें",
          "Analyze": "विश्लेषण",
          "Chat": "बात करना",
          "Select City": "शहर चुनें",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Home": "घर",
          "Created": "बनाया था",
          "Accepted": "को स्वीकृत",
          "Completed": "पूरा हुआ",
          "Rejected": "अस्वीकृत",
          "Cancelled": "रद्द",
          "Refunded": "वापसी की गई है",
          "Delayed": "देर से",
          "Inbox": "इनबॉक्स",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "Notification": "अधिसूचना",
          "Product Category": "उत्पाद श्रेणी",
          "Product Order History": "उत्पाद आदेश इतिहास",
          "Product Order Detail": "उत्पाद आदेश विवरण",
          "Work": "काम",
          "Others": "अन्य",
          "Status Updated": "स्थिति अपडेट",
          "Product Sub Category": "उत्पाद उप श्रेणी",
          "Reviews": "समीक्षा",
          "Served Category": "सेवित श्रेणी",
          "Select Service Category": "सेवा श्रेणी का चयन करें",
          "Service": "सेवा",
          "Service Detail": "सेवा विवरण",
          "My Slots": "मेरे स्लॉट",
          "Slot Remove Successfully": "स्लॉट सफलतापूर्वक निकालें",
          "Analytics": "एनालिटिक्स",
          "Profile": "प्रोफ़ाइल",
          "Welcome to Handyman Freelancer": "अप्रेंटिस फ्रीलांसर में आपका स्वागत है",
          "Door to Door Supprot": "डोर टू डोर सपोर्ट",
          "Easy Track Order": "आसान ट्रैक ऑर्डर",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.":
              "प्रकाशन और ग्राफिक डिजाइन में लोरेम इप्सम एक भराव पाठ है जिसे आमतौर पर प्रदर्शित करने के लिए उपयोग किया जाता है।",
          "Partner with Us": "हमारे साथ भागीदार",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Experience in year": "वर्ष में अनुभव",
          "Select Latitude & Longitude from here :": "यहां से अक्षांश और देशांतर चुनें:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "कृपया मान्य अक्षांश और देशांतर दर्ज करें अन्यथा ऐप ठीक से काम नहीं कर सकता है।",
          "Your Latitude": "आपका अक्षांश",
          "Your Longitude": "आपका देशांतर",
          "Sign up": "साइन अप करें",
          "Alredy have an account?": "क्या आपके पास खाता है?",
          "Phone number is required": "फ़ोन नंबर आवश्यक है",
          "Something went wrong while signup": "साइन अप करते समय कुछ गलत हुआ",
          "message": "संदेश",
          "Something went wrong": "कुछ गलत हो गया",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड को भेजा है",
          "Your Email is Verified": "आपका ईमेल सत्यापित है",
          "Please verify email": "कृपया ईमेल सत्यापित करें",
          "Please verify phone number": "कृपया फ़ोन नंबर सत्यापित करें",
          "Please upload your cover photo": "कृपया अपनी कवर फ़ोटो अपलोड करें",
          "password does not match": "पासवर्ड मैच नहीं कर रहा है",
          "Success!": "सफलता!",
          "Your Request is submitted": "आपका अनुरोध सबमिट किया गया है",
          "Okay": "ठीक",
          "Could not launch": "लॉन्च नहीं हो सका",
          "Verified": "सत्यापित",
          "Search": "खोज",
          "Start typing to search": "खोजने के लिए टाइप करना प्रारंभ करें",
          "Zipcode": "पिन कोड",
          "Email or phone Number": "ईमेल या फोन नंबर",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Phone Number": "फ़ोन नंबर",
          "Register": "पंजीकरण करवाना",
          "Access denied": "पहुंच अस्वीकृत",
          "Phone Number is required": "फ़ोन नंबर आवश्यक है",
          "Product Review": "उत्पाद समीक्षा",
          "About Us": "हमारे बारे में",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "FAQs": "पूछे जाने वाले प्रश्न",
          "Terms & Conditions": "नियम एवं शर्तें",
          "Privacy Policy": "गोपनीयता नीति",
          "Product Name": "प्रोडक्ट का नाम",
          "Daily": "रोज",
          "Monthly": "महीने के",
          "Yearly": "सालाना",
          "Appointment": "नियुक्ति",
          "Products Order": "उत्पाद आदेश",
          "Earnings": "आय",
          "Total": "कुल",
          "Average": "औसत",
          "Day": "दिन",
          "Bookings": "बुकिंग के",
          "Months": "महीने",
          "Total number of bookings": "बुकिंग की कुल संख्या",
          "Total number of orders": "आदेशों की कुल संख्या",
          "Full Name": "पूरा नाम",
          "Message": "संदेश",
          "camera": "कैमरा",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "अपना ईमेल पता या फोन नंबर दर्ज करें और हम एक नया पासवर्ड बनाने के लिए एक सत्यापन कोड भेजेंगे",
          "Generate New Password": "नया पासवर्ड जनरेट करें",
          "New Password": "नया पासवर्ड",
          "Update Password": "पासवर्ड अपडेट करें",
          "No Ongoing Appointments Found": "कोई चालू नियुक्ति नहीं मिली",
          "No Old Appointments Found": "कोई पुरानी नियुक्ति नहीं मिली",
          "No New Orders Found": "कोई नया आदेश नहीं मिला",
          "No Ongoing Orders Found": "कोई जारी आदेश नहीं मिला",
          "No Old Orders Found": "कोई पुराना आदेश नहीं मिला",
          "No Data Found": "कोई डेटा नहीं मिला",
          "January": "जनवरी",
          "February": "फ़रवरी",
          "March": "मार्च",
          "May": "मई",
          "June": "जून",
          "July": "जुलाई",
          "August": "अगस्त",
          "September": "सितंबर",
          "October": "अक्टूबर",
          "November": "नवंबर",
          "December": "दिसंबर",
          "April": "अप्रैल",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी गई",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध प्राप्त हो गया है, हम जल्द ही आपके मुद्दे पर प्रतिक्रिया देंगे",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल प्राप्त हुआ है",
          "New Contact Details": "नया संपर्क विवरण",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "Password Updated": "पासवर्ड अपडेट किया गया",
          "Fetching...": "लाया जा रहा है...",
          "Refreshing...": "रीफ़्रेश किया जा रहा है...",
          "Yes Delete": "हाँ हटाएं",
          "Are you sure?": "क्या आपको यकीन है?",
          "To delete this product": "इस उत्पाद को हटाने के लिए",
          "Yes Update": "हाँ अपडेट",
          "Change the status of this product": "इस उत्पाद की स्थिति बदलें",
          "Panding Payment": "लंबित भुगतान",
          "Product Reviews": "उत्पाद की समीक्षा",
          "To delete this service": "इस सेवा को हटाने के लिए",
          "Change the status of this service": "इस सेवा की स्थिति बदलें",
          "Session expired!": "सत्र समाप्त हुआ!",
        },
        'es_DE': {
          "Edit": "Editar",
          "My Services": "Mis servicios",
          "My Products": "Mis productos",
          "My Slot": "mi tragamonedas",
          "Review": "Revisar",
          "Language": "Idioma",
          "Change Password": "Cambia la contraseña",
          "Contact Us": "Contáctenos",
          "Chats": "charlas",
          "Help": "Ayuda",
          "About us": "Sobre nosotros",
          "Logout": "Cerrar sesión",
          "new": "nuevo",
          "Add New Product": "Añadir nuevo producto",
          "Update Product": "Actualizar producto",
          "Choose From": "Escoge de",
          "Camera": "Cámara",
          "Gallery": "Galería",
          "Cancel": "Cancelar",
          "product Name": "nombre del producto",
          "Select Category": "selecciona una categoría",
          "Select": "Seleccione",
          "Select Sub Category": "Seleccionar subcategoría",
          "Product price": "Precio del producto",
          "Discount": "Descuento",
          "Sell price": "Precio de venta",
          "Description": "Descripción",
          "Status": "Estado",
          "Active": "Activo",
          "Hide": "Ocultar",
          "Available": "Disponible",
          "In Stock": "En stock",
          "Out of Stock": "Agotado",
          "Is Single": "Es soltero",
          "In Offer": "En oferta",
          "Add Photos": "Agregar fotos",
          "In Gram": "en gramo",
          "Gram Value": "valor gramo",
          "In KG": "en kg",
          "KG Value": "Valor en kilogramos",
          "In Liter": "en litro",
          "Liter Value": "Valor de litro",
          "In PCs": "en pieza",
          "PCs Value": "Valor de la pieza",
          "In ML": "En ML",
          "ML Value": "Valor de aprendizaje automático",
          "Key Features": "Características clave",
          "Disclaimer": "Descargo de responsabilidad",
          "Submit": "Enviar",
          "Add New Service": "Agregar nuevo servicio",
          "Update Service": "Servicio de actualización",
          "Service Name": "Nombre del Servicio",
          "Service price": "precio del servicio",
          "Add New Slot": "Agregar nueva ranura",
          "Update Slot": "Actualizar ranura",
          "Sunday": "Domingo",
          "Monday": "Lunes",
          "Tuesday": "martes",
          "Wednesday": "miércoles",
          "Thursday": "jueves",
          "Friday": "Viernes",
          "Saturday": "sábado",
          "Open Time": "tiempo abierto",
          "Close Time": "Hora de cierre",
          "to": "a",
          "Are you sure": "Está seguro",
          "to delete this slot ?": "eliminar esta ranura?",
          "Delete": "Borrar",
          "Add Slot": "Agregar ranura",
          "Services": "Servicios",
          "Total Earning": "Ganancia total",
          "Total Service": "Servicio total",
          "Upcoming Services": "Próximos servicios",
          "Todays Service": "Servicio de hoy",
          "Products": "Productos",
          "Total Product": "Producto total",
          "Upcoming Products": "Próximos productos",
          "Todays Product": "Producto de hoy",
          "Chart": "Cuadro",
          "Message...": "Mensaje...",
          "Save": "Ahorrar",
          "Cancle": "Cancelar",
          "Email or phone number": "Correo electrónico o número de teléfono",
          "Password": "Clave",
          "Login": "Acceso",
          "First Name": "Primer nombre",
          "Last Name": "Apellido",
          "Male": "Masculino",
          "Gender": "Género",
          "Female": "Femenino",
          "Email": "Correo electrónico",
          "Code": "Código",
          "Phone": "Teléfono",
          "Freelancing Details": "Detalles del trabajo independiente",
          "Hourly Price": "Precio por hora",
          "Total Experience": "experiencia total",
          "Have Shop?": "¿Tienes Tienda?",
          "City ID": "Identificación de la ciudad",
          "Zip Code": "Código postal",
          "Latitude": "Latitud",
          "Longitude": "Longitud",
          "Connection Failed": "La conexión falló",
          "Could not connect to network": "No se pudo conectar a la red",
          "Please check and try again": "Por favor revisa e intenta de nuevo",
          "retry": "rever",
          "Verify": "Verificar",
          "Verification code": "Código de verificación",
          "An authentication code hase been sent to": "Se ha enviado un código de autenticación a",
          "OTP Verification": "Verificación OTP",
          "Send OTP": "Enviar OTP",
          "Email Address": "Dirección de correo electrónico",
          "Please enter your credentials": "Por favor ingrese sus credenciales",
          "Forgot Password": "Has olvidado tu contraseña",
          "New": "Nuevo",
          "Ongoing": "En curso",
          "Past": "Pasado",
          "Sign in": "Iniciar sesión",
          "Welcome Back!": "¡Bienvenido de nuevo!",
          "Order Details": "Detalles del pedido",
          "Order Number": "Número de orden",
          "Payment": "Pago",
          "Orders": "Pedidos",
          "Item Total": "Total",
          "Item discount": "descuento del artículo",
          "Delivery Charge": "Gastos de envío",
          "Taxes and Charges": "Impuestos y Cargos",
          "Grand Total": "Gran total",
          "Your Appoinments Status": "Estado de sus citas",
          "Your Order Status": "Estado de su pedido",
          "Accept": "Aceptar",
          "Decline": "Rechazar",
          "Update Status": "Estado de actualización",
          "ORDER": "ORDENAR",
          "Add+": "Agregar+",
          "edit": "editar",
          "Distance Charge": "Cargo por distancia",
          "Appointment Detail": "Detalle de la cita",
          "Appointment Number": "Número de cita",
          "Booking Details": "Detalles de la reserva",
          "Get Started": "Empezar",
          "to delete Slots ?": "eliminar las ranuras?",
          "Please wait": "Espere por favor",
          "No Internet Connection": "Sin conexión a Internet",
          "Continue with Phone Number": "Continuar con número de teléfono",
          "Continue with Email": "Continuar con correo electrónico",
          "Welcome to Handyman": "Bienvenido a Manitas",
          "My Account": "Mi cuenta",
          "Add Product": "Agregar producto",
          "Please select category first": "Seleccione la categoría primero",
          "All fields are required": "Todos los campos son obligatorios",
          "Addded": "Añadido",
          "update": "actualizar",
          "Discount must be less than 100": "El descuento debe ser inferior a 100",
          "Add Service": "Agregar servicio",
          "Slots are empty": "Las ranuras están vacías",
          "Already exist": "Ya existe",
          "Please select time": "Por favor seleccione hora",
          "Analyze": "Analizar",
          "Chat": "Charlar",
          "Select City": "Ciudad selecta",
          "Edit Profile": "Editar perfil",
          "Home": "Hogar",
          "Created": "Creado",
          "Accepted": "Aceptado",
          "Completed": "Terminado",
          "Rejected": "Rechazado",
          "Cancelled": "Cancelado",
          "Refunded": "Reintegrado",
          "Delayed": "Demorado",
          "Inbox": "Bandeja de entrada",
          "Email is not valid": "El correo no es válido",
          "Notification": "Notificación",
          "Product Category": "categoria de producto",
          "Product Order History": "Historial de pedidos de productos",
          "Product Order Detail": "Detalle del pedido del producto",
          "Work": "Trabajar",
          "Others": "Otros",
          "Status Updated": "Estado actualizado",
          "Product Sub Category": "Subcategoría de producto",
          "Reviews": "Reseñas",
          "Served Category": "Categoría servida",
          "Select Service Category": "Seleccionar categoría de servicio",
          "Service": "Servicio",
          "Service Detail": "Detalle del servicio",
          "My Slots": "Mis tragamonedas",
          "Slot Remove Successfully": "Eliminación de ranura con éxito",
          "Analytics": "Analítica",
          "Profile": "Perfil",
          "Welcome to Handyman Freelancer": "Bienvenido a Handyman Freelancer",
          "Door to Door Supprot": "Soporte puerta a puerta",
          "Easy Track Order": "Orden de seguimiento fácil",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.":
              "En publicaciones y diseño gráfico, lorem ipsum es un texto de relleno comúnmente utilizado para demostrar.",
          "Partner with Us": "Asóciese con nosotros",
          "Confirm Password": "Confirmar contraseña",
          "Experience in year": "Experiencia en año",
          "Select Latitude & Longitude from here :": "Seleccione Latitud y Longitud desde aquí:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.":
              "Ingrese una latitud y longitud válidas; de lo contrario, es posible que la aplicación no funcione correctamente.",
          "Your Latitude": "tu latitud",
          "Your Longitude": "tu longitud",
          "Sign up": "Inscribirse",
          "Alredy have an account?": "¿Ya tienes una cuenta?",
          "Phone number is required": "Se requiere el número de teléfono",
          "Something went wrong while signup": "Algo salió mal durante el registro",
          "message": "mensaje",
          "Something went wrong": "Algo salió mal",
          "Verification": "Verificación",
          "We have sent verification code on": "Hemos enviado el código de verificación el",
          "Your Email is Verified": "Su correo electrónico está verificado",
          "Please verify email": "Verifique el correo electrónico",
          "Please verify phone number": "Por favor verifique el número de teléfono",
          "Please upload your cover photo": "Por favor sube tu foto de portada",
          "password does not match": "las contraseñas no coinciden",
          "Success!": "¡Éxito!",
          "Your Request is submitted": "Su solicitud ha sido enviada",
          "Okay": "De acuerdo",
          "Could not launch": "no se pudo iniciar",
          "Verified": "Verificado",
          "Search": "Búsqueda",
          "Start typing to search": "Empieza a escribir para buscar",
          "Zipcode": "Código postal",
          "Email or phone Number": "Correo electrónico o número de teléfono",
          "Forgot Password?": "¿Has olvidado tu contraseña?",
          "Phone Number": "Número de teléfono",
          "Register": "Registro",
          "Access denied": "Acceso denegado",
          "Phone Number is required": "Se requiere número de teléfono",
          "Product Review": "Revision de producto",
          "About Us": "Sobre nosotros",
          "Frequently Asked Questions": "Preguntas frecuentes",
          "FAQs": "preguntas frecuentes",
          "Terms & Conditions": "Términos y condiciones",
          "Privacy Policy": "Política de privacidad",
          "Product Name": "nombre del producto",
          "Daily": "Diariamente",
          "Monthly": "Mensual",
          "Yearly": "Anual",
          "Appointment": "Cita",
          "Products Order": "Pedido de productos",
          "Earnings": "Ganancias",
          "Total": "Total",
          "Average": "Promedio",
          "Day": "Día",
          "Bookings": "Reservaciones",
          "Months": "Meses",
          "Total number of bookings": "Número total de reservas",
          "Total number of orders": "Número total de pedidos",
          "Full Name": "Nombre completo",
          "Message": "Mensaje",
          "camera": "cámara",
          "Verify your phone number": "verifica tu numero de telefono",
          "Reset Password": "Restablecer la contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":
              "Ingrese su dirección de correo electrónico o número de teléfono y le enviaremos un código de verificación para generar una nueva contraseña",
          "Generate New Password": "Generar nueva contraseña",
          "New Password": "Nueva contraseña",
          "Update Password": "Actualiza contraseña",
          "No Ongoing Appointments Found": "No se encontraron citas en curso",
          "No Old Appointments Found": "No se encontraron citas antiguas",
          "No New Orders Found": "No se encontraron nuevos pedidos",
          "No Ongoing Orders Found": "No se encontraron pedidos en curso",
          "No Old Orders Found": "No se encontraron pedidos antiguos",
          "No Data Found": "Datos no encontrados",
          "January": "enero",
          "February": "Febrero",
          "March": "Marzo",
          "May": "Mayo",
          "June": "Junio",
          "July": "Julio",
          "August": "Agosto",
          "September": "Septiembre",
          "October": "Octubre",
          "November": "Noviembre",
          "December": "Diciembre",
          "April": "Abril",
          "Alert!": "¡Alerta!",
          "Contact Information Sent": "Información de contacto enviada",
          "We have received your request, we will respond on your issue soon": "Hemos recibido tu solicitud, pronto responderemos a tu problema.",
          "New Mail Request Received": "Nueva solicitud de correo recibida",
          "You have received new mail": "Has recibido correo nuevo",
          "New Contact Details": "Nuevos detalles de contacto",
          "Password mismatch": "Contraseña no coincide",
          "Password Updated": "Contraseña actualiza",
          "Fetching...": "Atractivo...",
          "Refreshing...": "Refrescante...",
          "Yes Delete": "Sí Eliminar",
          "Are you sure?": "¿Está seguro?",
          "To delete this product": "Para eliminar este producto",
          "Yes Update": "Sí Actualizar",
          "Change the status of this product": "Cambiar el estado de este producto",
          "Panding Payment": "Pago pendiente",
          "Product Reviews": "Reseñas de productos",
          "To delete this service": "Para eliminar este servicio",
          "Change the status of this service": "Cambiar el estado de este servicio",
          "Session expired!": "¡Sesión expirada!",
        },
        'ar_AE': {
          "Edit": "يحرر",
          "My Services": "خدماتي",
          "My Products": "منتجاتي",
          "My Slot": "فتحة بلدي",
          "Review": "إعادة النظر",
          "Language": "لغة",
          "Change Password": "غير كلمة السر",
          "Contact Us": "اتصل بنا",
          "Chats": "الدردشات",
          "Help": "مساعدة",
          "About us": "معلومات عنا",
          "Logout": "تسجيل خروج",
          "new": "الجديد",
          "Add New Product": "اضافة منتج جديد",
          "Update Product": "تحديث المنتج",
          "Choose From": "اختر من",
          "Camera": "آلة تصوير",
          "Gallery": "صالة عرض",
          "Cancel": "يلغي",
          "product Name": "اسم المنتج",
          "Select Category": "اختر الفئة",
          "Select": "يختار",
          "Select Sub Category": "حدد الفئة الفرعية",
          "Product price": "سعر المنتج",
          "Discount": "تخفيض",
          "Sell price": "سعر البيع",
          "Description": "وصف",
          "Status": "حالة",
          "Active": "نشيط",
          "Hide": "يخفي",
          "Available": "متوفرة",
          "In Stock": "في الأوراق المالية",
          "Out of Stock": "إنتهى من المخزن",
          "Is Single": "هو وحيد",
          "In Offer": "في العرض",
          "Add Photos": "إضافة الصور",
          "In Gram": "بالجرام",
          "Gram Value": "قيمة الجرام",
          "In KG": "في KG",
          "KG Value": "قيمة KG",
          "In Liter": "باللتر",
          "Liter Value": "قيمة اللتر",
          "In PCs": "في قطعة",
          "PCs Value": "قيمة القطعة",
          "In ML": "في ML",
          "ML Value": "قيمة ML",
          "Key Features": "دلائل الميزات",
          "Disclaimer": "تنصل",
          "Submit": "يُقدِّم",
          "Add New Service": "أضف خدمة جديدة",
          "Update Service": "تحديث الخدمة",
          "Service Name": "اسم الخدمة",
          "Service price": "سعر الخدمة",
          "Add New Slot": "أضف فتحة جديدة",
          "Update Slot": "فتحة التحديث",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "يوم الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "يوم الخميس",
          "Friday": "جمعة",
          "Saturday": "السبت",
          "Open Time": "وقت متاح",
          "Close Time": "وقت الاغلاق",
          "to": "إلى",
          "Are you sure": "هل أنت واثق",
          "to delete this slot ?": "لحذف هذه الفتحة؟",
          "Delete": "حذف",
          "Add Slot": "أضف فتحة",
          "Services": "خدمات",
          "Total Earning": "مجموع الأرباح",
          "Total Service": "إجمالي الخدمة",
          "Upcoming Services": "الخدمات القادمة",
          "Todays Service": "خدمة اليوم",
          "Products": "منتجات",
          "Total Product": "إجمالي المنتج",
          "Upcoming Products": "المنتجات القادمة",
          "Todays Product": "منتج اليوم",
          "Chart": "جدول",
          "Message...": "رسالة...",
          "Save": "يحفظ",
          "Cancle": "إلغاء",
          "Email or phone number": "البريد الإلكتروني أو رقم الهاتف",
          "Password": "كلمة المرور",
          "Login": "تسجيل الدخول",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Male": "ذكر",
          "Gender": "جنس",
          "Female": "أنثى",
          "Email": "البريد الإلكتروني",
          "Code": "شفرة",
          "Phone": "هاتف",
          "Freelancing Details": "تفاصيل العمل الحر",
          "Hourly Price": "السعر بالساعة",
          "Total Experience": "عدد سنوات الخبرة",
          "Have Shop?": "هل لديك متجر؟",
          "City ID": "معرف المدينة",
          "Zip Code": "الرمز البريدي",
          "Latitude": "خط العرض",
          "Longitude": "خط الطول",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "تعذر الاتصال بالشبكة",
          "Please check and try again": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "أعد المحاولة",
          "Verify": "يؤكد",
          "Verification code": "رمز التحقق",
          "An authentication code hase been sent to": "تم إرسال رمز المصادقة إلى",
          "OTP Verification": "التحقق من OTP",
          "Send OTP": "أرسل OTP",
          "Email Address": "عنوان البريد الالكترونى",
          "Please enter your credentials": "الرجاء إدخال بيانات الاعتماد الخاصة بك",
          "Forgot Password": "هل نسيت كلمة السر",
          "New": "جديد",
          "Ongoing": "جاري التنفيذ",
          "Past": "ماضي",
          "Sign in": "تسجيل الدخول",
          "Welcome Back!": "مرحبًا بعودتك!",
          "Order Details": "تفاصيل الطلب",
          "Order Number": "رقم الطلب",
          "Payment": "دفع",
          "Orders": "الطلب #٪ s",
          "Item Total": "مجموع الاشياء",
          "Item discount": "خصم البند",
          "Delivery Charge": "رسوم التوصيل",
          "Taxes and Charges": "الضرائب والرسوم",
          "Grand Total": "المبلغ الإجمالي",
          "Your Appoinments Status": "حالة المواعيد الخاصة بك",
          "Your Order Status": "حالة طلبك",
          "Accept": "قبول",
          "Decline": "انخفاض",
          "Update Status": "تحديث الحالة",
          "ORDER": "ترتيب",
          "Add+": "أضف +",
          "edit": "تعديل",
          "Distance Charge": "المسافة تهمة",
          "Appointment Detail": "تفاصيل الموعد",
          "Appointment Number": "رقم الموعد",
          "Booking Details": "تفاصيل الحجز",
          "Get Started": "البدء",
          "to delete Slots ?": "لحذف الفتحات؟",
          "Please wait": "أرجو الإنتظار",
          "No Internet Connection": "لا يوجد اتصال بالإنترنت",
          "Continue with Phone Number": "تواصل مع رقم الهاتف",
          "Continue with Email": "تواصل مع البريد الإلكتروني",
          "Welcome to Handyman": "مرحبا بكم في Handyman",
          "My Account": "حسابي",
          "Add Product": "أضف منتج",
          "Please select category first": "الرجاء تحديد الفئة أولاً",
          "All fields are required": "جميع الحقول مطلوبة",
          "Addded": "مضاف",
          "update": "تحديث",
          "Discount must be less than 100": "يجب أن يكون الخصم أقل من 100",
          "Add Service": "أضف خدمة",
          "Slots are empty": "الفتحات فارغة",
          "Already exist": "موجود مسبقا",
          "Please select time": "الرجاء تحديد الوقت",
          "Analyze": "حلل",
          "Chat": "دردشة",
          "Select City": "اختر مدينة",
          "Edit Profile": "تعديل الملف الشخصي",
          "Home": "مسكن",
          "Created": "مخلوق",
          "Accepted": "وافقت",
          "Completed": "مكتمل",
          "Rejected": "مرفوض",
          "Cancelled": "ألغيت",
          "Refunded": "معاد",
          "Delayed": "تأخير",
          "Inbox": "صندوق الوارد",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Notification": "تنبيه",
          "Product Category": "فئة المنتج",
          "Product Order History": "تاريخ طلب المنتج",
          "Product Order Detail": "تفاصيل طلب المنتج",
          "Work": "عمل",
          "Others": "آحرون",
          "Status Updated": "تم تحديث الحالة",
          "Product Sub Category": "فئة المنتج الفرعية",
          "Reviews": "المراجعات",
          "Served Category": "فئة الخدمة",
          "Select Service Category": "حدد فئة الخدمة",
          "Service": "خدمة",
          "Service Detail": "تفاصيل الخدمة",
          "My Slots": "فتحات بلدي",
          "Slot Remove Successfully": "تمت إزالة الفتحة بنجاح",
          "Analytics": "تحليلات",
          "Profile": "الملف الشخصي",
          "Welcome to Handyman Freelancer": "مرحبًا بكم في Handyman Freelancer",
          "Door to Door Supprot": "دعم من الباب الى الباب",
          "Easy Track Order": "ترتيب سهل التعقب",
          "In publishing and graphic design lorem ipsum is a filler text commonly used to demonstrate.": "في النشر والتصميم الجرافيكي ، يعد lorem ipsum نصًا حشوًا يشيع استخدامه للتوضيح.",
          "Partner with Us": "شريك معنا",
          "Confirm Password": "تأكيد كلمة المرور",
          "Experience in year": "خبرة في العام",
          "Select Latitude & Longitude from here :": "حدد خط الطول وخط العرض من هنا:",
          "Please enter valid Latitude & Longitude otherwise app may not work properly.": "الرجاء إدخال خط الطول وخط العرض صالحين وإلا فقد لا يعمل التطبيق بشكل صحيح.",
          "Your Latitude": "خط العرض الخاص بك",
          "Your Longitude": "خط الطول الخاص بك",
          "Sign up": "اشتراك",
          "Alredy have an account?": "الريدي لديك حساب؟",
          "Phone number is required": "رقم الهاتف مطلوب",
          "Something went wrong while signup": "حدث خطأ ما أثناء التسجيل",
          "message": "رسالة",
          "Something went wrong": "هناك خطأ ما",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Your Email is Verified": "تم التحقق من بريدك الإلكتروني",
          "Please verify email": "يرجى التحقق من البريد الإلكتروني",
          "Please verify phone number": "الرجاء التحقق من رقم الهاتف",
          "Please upload your cover photo": "يرجى تحميل صورة الغلاف الخاصة بك",
          "password does not match": "كلمة السر غير متطابقة",
          "Success!": "النجاح!",
          "Your Request is submitted": "تم تقديم طلبك",
          "Okay": "تمام",
          "Could not launch": "تعذر الإطلاق",
          "Verified": "تم التحقق",
          "Search": "يبحث",
          "Start typing to search": "ابدأ الكتابة للبحث",
          "Zipcode": "الرمز البريدي",
          "Email or phone Number": "البريد الإلكتروني أو رقم الهاتف",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Phone Number": "رقم الهاتف",
          "Register": "يسجل",
          "Access denied": "تم الرفض",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Product Review": "تقييم المنتج",
          "About Us": "معلومات عنا",
          "Frequently Asked Questions": "أسئلة مكررة",
          "FAQs": "أسئلة وأجوبة",
          "Terms & Conditions": "البنود و الظروف",
          "Privacy Policy": "سياسة الخصوصية",
          "Product Name": "اسم المنتج",
          "Daily": "اليومي",
          "Monthly": "شهريا",
          "Yearly": "سنوي",
          "Appointment": "ميعاد",
          "Products Order": "ترتيب المنتجات",
          "Earnings": "أرباح",
          "Total": "المجموع",
          "Average": "متوسط",
          "Day": "يوم",
          "Bookings": "الحجوزات",
          "Months": "شهور",
          "Total number of bookings": "إجمالي عدد الحجوزات",
          "Total number of orders": "إجمالي عدد الطلبات",
          "Full Name": "الاسم الكامل",
          "Message": "رسالة",
          "camera": "كاميرا",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز تحقق لإنشاء كلمة مرور جديدة",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Update Password": "تطوير كلمة السر",
          "No Ongoing Appointments Found": "لم يتم العثور على مواعيد جارية",
          "No Old Appointments Found": "لم يتم العثور على مواعيد قديمة",
          "No New Orders Found": "لم يتم العثور على طلبات جديدة",
          "No Ongoing Orders Found": "لم يتم العثور على أوامر جارية",
          "No Old Orders Found": "لم يتم العثور على أوامر قديمة",
          "No Data Found": "لاتوجد بيانات",
          "January": "يناير",
          "February": "شهر فبراير",
          "March": "يمشي",
          "May": "مايو",
          "June": "يونيه",
          "July": "يوليو",
          "August": "أغسطس",
          "September": "سبتمبر",
          "October": "اكتوبر",
          "November": "شهر نوفمبر",
          "December": "ديسمبر",
          "April": "أبريل",
          "Alert!": "انذار!",
          "Contact Information Sent": "تم إرسال معلومات الاتصال",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسنرد على مشكلتك قريبًا",
          "New Mail Request Received": "تم استلام طلب بريد جديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل جهة اتصال جديدة",
          "Password mismatch": "كلمة المرور غير متطابقة",
          "Password Updated": "تم تحديث كلمة السر",
          "Fetching...": "إحضار ...",
          "Refreshing...": "منعش...",
          "Yes Delete": "نعم احذف",
          "Are you sure?": "هل أنت واثق؟",
          "To delete this product": "لحذف هذا المنتج",
          "Yes Update": "نعم التحديث",
          "Change the status of this product": "قم بتغيير حالة هذا المنتج",
          "Panding Payment": "الدفع Panding",
          "Product Reviews": "تعليقات المنتج",
          "To delete this service": "لحذف هذه الخدمة",
          "Change the status of this service": "قم بتغيير حالة هذه الخدمة",
          "Session expired!": "انتهت الجلسة!",
        },
      };
}
